# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.aamva_detailed_match_result import AAMVADetailedMatchResult
from plaid_skel.models.aamva_match_result import AAMVAMatchResult




class AAMVAAnalysis(BaseModel):
    """Analyzed AAMVA data for the associated hit.  Note: This field is only available for U.S. driver's licenses issued by participating states."""

    model_config = ConfigDict(json_schema_extra={"nullable": True})

    is_verified: bool = Field( description="The overall outcome of checking the associated hit against the issuing state database.")
    id_number: AAMVAMatchResult = Field()
    id_issue_date: AAMVAMatchResult = Field()
    id_expiration_date: AAMVAMatchResult = Field()
    street: AAMVADetailedMatchResult = Field()
    city: AAMVAMatchResult = Field()
    postal_code: AAMVADetailedMatchResult = Field()
    date_of_birth: AAMVAMatchResult = Field()
    gender: AAMVAMatchResult = Field()
    height: AAMVAMatchResult = Field()
    eye_color: AAMVAMatchResult = Field()
    first_name: AAMVADetailedMatchResult = Field()
    middle_name: AAMVADetailedMatchResult = Field()
    last_name: AAMVADetailedMatchResult = Field()

AAMVAAnalysis.update_forward_refs()
