# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.asset_report_transaction import AssetReportTransaction
from plaid_skel.models.historical_balance import HistoricalBalance
from plaid_skel.models.owner import Owner
from plaid_skel.models.ownership_type import OwnershipType




class AccountAssetsAllOf(BaseModel):
    """"""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#account_assets_all_of"
            }
        }

    days_available: Optional[float] = Field(default=None, description="The duration of transaction history available for this Item, typically defined as the time since the date of the earliest transaction in that account. Only returned by Assets endpoints.")
    transactions: Optional[List[AssetReportTransaction]] = Field(default=None, description="Transaction history associated with the account. Only returned by Assets endpoints. Transaction history returned by endpoints such as `/transactions/get` or `/investments/transactions/get` will be returned in the top-level `transactions` field instead.")
    owners: Optional[List[Owner]] = Field(default=None, description="Data returned by the financial institution about the account owner or owners. Only returned by Identity or Assets endpoints. For business accounts, the name reported may be either the name of the individual or the name of the business, depending on the institution. Multiple owners on a single account will be represented in the same `owner` object, not in multiple owner objects within the array. In API versions 2018-05-22 and earlier, the `owners` object is not returned, and instead identity information is returned in the top level `identity` object. For more details, see [Plaid API versioning](https://plaid.com/docs/api/versioning/#version-2019-05-29)")
    ownership_type: Optional[OwnershipType] = Field(default=None,)
    historical_balances: Optional[List[HistoricalBalance]] = Field(default=None, description="Calculated data about the historical balances on the account. Only returned by Assets endpoints and currently not supported by `brokerage` or `investment` accounts.")

AccountAssetsAllOf.update_forward_refs()
