# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class AccountFilter(BaseModel):
    """Enumerates the account subtypes that the application wishes for the user to be able to select from. For more details refer to Plaid documentation on account filters."""


    depository: Optional[List[str]] = Field(default=None, description="A list of account subtypes to be filtered.")
    credit: Optional[List[str]] = Field(default=None, description="A list of account subtypes to be filtered.")
    loan: Optional[List[str]] = Field(default=None, description="A list of account subtypes to be filtered.")
    investment: Optional[List[str]] = Field(default=None, description="A list of account subtypes to be filtered.")

AccountFilter.update_forward_refs()
