# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum



class ActionState(str, Enum):
    UNKNOWN = "UNKNOWN"
    ATTEMPT = "ATTEMPT"
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    SKIPPED = "SKIPPED"
