# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import ConfigDict, AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class AddressDataNullable(BaseModel):
    """Data about the components comprising an address."""
    model_config = ConfigDict(json_schema_extra={"nullable": True})

    city: Optional[str] = Field(default=None, description="The full city name")
    region: Optional[str] = Field(default=None, description="The region or state. In API versions 2018-05-22 and earlier, this field is called `state`. Example: `\"NC\"`")
    street: str = Field( description="The full street address Example: `\"564 Main Street, APT 15\"`")
    postal_code: Optional[str] = Field(default=None, description="The postal code. In API versions 2018-05-22 and earlier, this field is called `zip`.")
    country: Optional[str] = Field(default=None, description="The ISO 3166-1 alpha-2 country code")

AddressDataNullable.update_forward_refs()
