# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.webhook_environment_values import WebhookEnvironmentValues




class AssetsProductReadyWebhook(BaseModel):
    """Fired when the Asset Report has been generated and `/asset_report/get` is ready to be called.  If you attempt to retrieve an Asset Report before this webhook has fired, you’ll receive a response with the HTTP status code 400 and a Plaid error code of `PRODUCT_NOT_READY`."""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#assets_product_ready_webhook"
            }
        }

    webhook_type: str = Field( description="`ASSETS`")
    webhook_code: str = Field( description="`PRODUCT_READY`")
    asset_report_id: str = Field( description="The `asset_report_id` corresponding to the Asset Report the webhook has fired for.")
    report_type: Optional[str] = Field(default=None, description="The report type, indicating whether the Asset Report is a `full` or `fast` report.")
    environment: WebhookEnvironmentValues = Field()

AssetsProductReadyWebhook.update_forward_refs()
