# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class AssetHolding(BaseModel):
    """Documentation not found in the MISMO model viewer and not provided by Freddie Mac."""


    asset_holding_id: Optional[str] = Field(default=None, description="Unique id of investment position")
    currency: Optional[str] = Field(default=None, description="US Dollar")
    asset_holding_description: Optional[str] = Field(default=None, description="Description of holding")
    asset_holding_symbol: Optional[str] = Field(default=None, description="Investment position's market ticker symbol")
    asset_holding_security_name: Optional[str] = Field(default=None, description="Security name of investment holding")
    asset_holding_units: Optional[float] = Field(default=None, description="Number of units of holding")
    asset_holding_market_value_amount: Optional[float] = Field(default=None, description="market value of investment position")
    asset_holding_current_price_amount: Optional[float] = Field(default=None, description="current price of investment holding")
    asset_holding_type: Optional[str] = Field(default=None, description="Type of holding (e.g. bond, stock, crypto, other)")
    asset_holding_restricted_indicator: Optional[str] = Field(default=None, description="Whether or not the stock is restricted, i.e. \"Restricted\" or \"Not Restricted\"")
    asset_holding_vested_amount: Optional[float] = Field(default=None, description="Amount of holding vested")

AssetHolding.update_forward_refs()
