# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.asset_type import AssetType




class AssetDetail(BaseModel):
    """Details about an asset."""


    asset_unique_identifier: str = Field( description="A vendor created unique Identifier.")
    asset_account_identifier: str = Field( description="A unique alphanumeric string identifying an asset.")
    asset_as_of_date: str = Field( description="Account Report As of Date / Create Date. Format YYYY-MM-DD")
    asset_description: Optional[str] = Field(default=None, description="A text description that further defines the Asset. This could be used to describe the shares associated with the stocks, bonds or mutual funds, retirement funds or business owned that the borrower has disclosed (named) as an asset.")
    asset_available_balance_amount: float = Field( description="Asset Account Available Balance.")
    asset_current_balance_amount: float = Field( description="A vendor created unique Identifier")
    asset_holding_balance_amount: Optional[float] = Field(default=None, description="Total market value of holdings (non-restricted, vested, not crypto, not other, not cash) Note: Any employer stock plan balance must be excluded from the total account balance (identification is 'stock plan')")
    asset_holding_balance_net_margin_amount: Optional[float] = Field(default=None, description="HoldingsBalance net MarginAmount")
    asset_bonds_balance_amount: Optional[float] = Field(default=None, description="Total market value of all bonds held (non-restricted, vested)")
    asset_stocks_balance_amount: Optional[float] = Field(default=None, description="Total market value of all stocks held (non-restricted, vested, not employer sponsored stock plan)")
    asset_crypto_balance_amount: Optional[float] = Field(default=None, description="Total balance of all cryptocurrency held (non-restricted, vested)")
    asset_other_balance_amount: Optional[float] = Field(default=None, description="Total balance of all other holding types (non-restricted, vested)")
    asset_margin_amount_balance: Optional[float] = Field(default=None, description="loan balance (amount owed by account owner)")
    asset_available_cash_balance_amount: Optional[float] = Field(default=None, description="amount available for cash withdrawal")
    asset_cash_balance_amount: Optional[float] = Field(default=None, description="cash balance of the account")
    asset_type: AssetType = Field()
    asset_type_additional_description: Optional[str] = Field(default=None, description="Additional Asset Decription some examples are Investment Tax-Deferred , Loan, 401K, 403B, Checking, Money Market, Credit Card,ROTH,529,Biller,ROLLOVER,CD,Savings,Investment Taxable, IRA, Mortgage, Line Of Credit.")
    asset_days_requested_count: int = Field( description="The Number of days requested made to the Financial Institution. Example When looking for 3 months of data from the FI, pass in 90 days.")
    asset_ownership_type: Optional[str] = Field(default=None, description="Ownership type of the asset account.")
    asset_retirement_indicator: Optional[str] = Field(default=None, description="Whether or not the account is a retirement account (e.g., 401K, 403b, 457, thrift savings plans, traditional and Roth, IRAs, SEP-IRA, SIMPLE-IRA, KEOGH, state retirement savings plans, other independent and IRS-qualified employer retirement plans)")
    asset_employer_sponsored_indicator: Optional[str] = Field(default=None, description="Whether the account is employer sponsored retirement account or not (e.g., 401K, 403b, 457, thrift savings plan)")

AssetDetail.update_forward_refs()
