# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.credit_category import CreditCategory




class AssetReportTransactionAllOf(BaseModel):
    """"""


    date_transacted: Optional[str] = Field(default=None, description="The date on which the transaction took place, in IS0 8601 format.")
    credit_category: Optional[CreditCategory] = Field(default=None,)

AssetReportTransactionAllOf.update_forward_refs()
