# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.asset_report_create_request_options import AssetReportCreateRequestOptions




class AssetReportCreateRequest(BaseModel):
    """AssetReportCreateRequest defines the request schema for `/asset_report/create`"""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#asset_report_create_request"
            }
        }

    client_id: Optional[str] = Field(default=None, description="Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.")
    secret: Optional[str] = Field(default=None, description="Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.")
    access_tokens: Optional[List[str]] = Field(default=None, description="An array of access tokens corresponding to the Items that will be included in the report. The `assets` product must have been initialized for the Items during link; the Assets product cannot be added after initialization.")
    user_token: Optional[str] = Field(default=None, description="The user token associated with the User for which to create an asset report for. All items associated with the User will be included in the report.")
    days_requested: int = Field( description="The maximum integer number of days of history to include in the Asset Report. If using Fannie Mae Day 1 Certainty, `days_requested` must be at least 61 for new originations or at least 31 for refinancings.  An Asset Report requested with \"Additional History\" (that is, with more than 61 days of transaction history) will incur an Additional History fee.")
    options: Optional[AssetReportCreateRequestOptions] = Field(default=None,)

    @validator("days_requested")
    def days_requested_max(cls, value):
        assert value <= 731
        return value

    @validator("days_requested")
    def days_requested_min(cls, value):
        assert value >= 0
        return value

AssetReportCreateRequest.update_forward_refs()
