# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from strenum import StrEnum

BankTransferStatus = StrEnum("BankTransferStatus", names=['pending', 'posted', 'cancelled', 'failed', 'reversed'])