# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.base_report_warning_code import BaseReportWarningCode
from plaid_skel.models.cause import Cause




class BaseReportWarning(BaseModel):
    """It is possible for a Base Report to be returned with missing account owner information. In such cases, the Base Report will contain warning data in the response, indicating why obtaining the owner information failed."""


    warning_type: str = Field( description="The warning type, which will always be `BASE_REPORT_WARNING`")
    warning_code: BaseReportWarningCode = Field()
    cause: Optional[Cause] = Field(default=None,)

BaseReportWarning.update_forward_refs()
