# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.base_report_item import BaseReportItem




class BaseReport(BaseModel):
    """An object representing a Base Report"""


    report_id: str = Field( description="A unique ID identifying an Base Report. Like all Plaid identifiers, this ID is case sensitive.")
    date_generated: datetime_ = Field( description="The date and time when the Base Report was created, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (e.g. \"2018-04-12T03:32:11Z\").")
    days_requested: float = Field( description="The number of days of transaction history requested.")
    items: List[BaseReportItem] = Field( description="Data returned by Plaid about each of the Items included in the Base Report.")

BaseReport.update_forward_refs()
