# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.plaid_error import PlaidError
from plaid_skel.models.webhook_environment_values import WebhookEnvironmentValues




class BaseReportsErrorWebhook(BaseModel):
    """Fired when Base Report generation has failed. The resulting `error` will have an `error_type` of `BASE_REPORT_ERROR`."""


    webhook_type: str = Field( description="`BASE_REPORT`")
    webhook_code: str = Field( description="`ERROR`")
    error: Optional[PlaidError] = Field(default=None,)
    user_id: str = Field( description="The `user_id` corresponding to the User ID the webhook has fired for.")
    environment: WebhookEnvironmentValues = Field()

BaseReportsErrorWebhook.update_forward_refs()
