# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class BaseReportNumberFlowInsights(BaseModel):
    """The number of credits or debits out of the account. This field will only added for depository accounts"""


    start_date: Optional[str] = Field(default=None, description="The start date of this time period. The date will be returned in an ISO 8601 format (YYYY-MM-DD).")
    end_date: Optional[str] = Field(default=None, description="The end date of this time period. The date will be returned in an ISO 8601 format (YYYY-MM-DD).")
    count: Optional[int] = Field(default=None, description="The number of credits or debits out of the account for this time period.")

BaseReportNumberFlowInsights.update_forward_refs()
