# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.webhook_environment_values import WebhookEnvironmentValues




class BaseReportsProductReadyWebhook(BaseModel):
    """Fired when the Base Report has been generated and `/cra/base_report/get` is ready to be called.  If you attempt to retrieve a Base Report before this webhook has fired, you’ll receive a response with the HTTP status code 400 and a Plaid error code of `PRODUCT_NOT_READY`."""


    webhook_type: str = Field( description="`BASE_REPORT`")
    webhook_code: str = Field( description="`PRODUCT_READY`")
    user_id: str = Field( description="The `user_id` corresponding to the User ID the webhook has fired for.")
    environment: WebhookEnvironmentValues = Field()

BaseReportsProductReadyWebhook.update_forward_refs()
