# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum


class BeaconUserStatus(str, Enum):
    REJECTED = "rejected"
    PENDING_REVIEW = "pending_review"
    CLEARED = "cleared"
