# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.account_subtype import AccountSubtype
from plaid_skel.models.account_type import AccountType
from plaid_skel.models.beacon_account_risk_evaluate_account_attributes import BeaconAccountRiskEvaluateAccountAttributes




class BeaconAccountRiskEvaluateAccount(BaseModel):
    """An account in the `/beacon/account_risk/v1/evaluate` response."""


    account_id: Optional[str] = Field(default=None, description="The account ID.")
    type: Optional[AccountType] = Field(default=None,)
    subtype: Optional[AccountSubtype] = Field(default=None,)
    attributes: Optional[BeaconAccountRiskEvaluateAccountAttributes] = Field(default=None,)

BeaconAccountRiskEvaluateAccount.update_forward_refs()
