# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class BeaconUserDepositoryAccount(BaseModel):
    """Depository account information for the associated user."""


    account_mask: str = Field( description="The last 2-4 numeric characters of this account’s account number.")
    routing_number: str = Field( description="The routing number of the account.")
    added_at: datetime_ = Field( description="An ISO8601 formatted timestamp.")

BeaconUserDepositoryAccount.update_forward_refs()
