# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.beacon_user_id_number import BeaconUserIDNumber
from plaid_skel.models.beacon_user_name_nullable import BeaconUserNameNullable
from plaid_skel.models.beacon_user_request_address_nullable import BeaconUserRequestAddressNullable
from plaid_skel.models.beacon_user_request_depository_account import BeaconUserRequestDepositoryAccount




class BeaconUserUpdateRequestData(BaseModel):
    """A subset of a Beacon User's data which is used to patch the existing identity data associated with a Beacon User. At least one field must be provided. If left unset or null, user data will not be patched."""

    model_config = ConfigDict(json_schema_extra={"nullable": True})

    date_of_birth: Optional[date_] = Field(default=None, description="A date in the format YYYY-MM-DD (RFC 3339 Section 5.6).")
    name: Optional[BeaconUserNameNullable] = Field(default=None,)
    address: Optional[BeaconUserRequestAddressNullable] = Field(default=None,)
    email_address: Optional[EmailStr] = Field(default=None, description="A valid email address. Must not have leading or trailing spaces and address must be RFC compliant. For more information, see [RFC 3696](https://datatracker.ietf.org/doc/html/rfc3696).")
    phone_number: Optional[str] = Field(default=None, description="A phone number in E.164 format.")
    id_number: Optional[BeaconUserIDNumber] = Field(default=None,)
    ip_address: Optional[str] = Field(default=None, description="An IPv4 or IPV6 address.")
    depository_accounts: Optional[List[BeaconUserRequestDepositoryAccount]] = Field(default=None,)

BeaconUserUpdateRequestData.update_forward_refs()
