# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum



class BeaconAuditTrailSource(str, Enum):
    DASHBOARD = "dashboard"
    API = "api"
    SYSTEM = "system"
    BULK_IMPORT = "bulk_import"
