# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.webhook_environment_values import WebhookEnvironmentValues




class BeaconUserStatusUpdatedWebhook(BaseModel):
    """Fired when a Beacon User status has changed, which can occur manually via the dashboard or when information is reported to the Beacon network."""


    webhook_type: str = Field( description="`BEACON`")
    webhook_code: str = Field( description="`USER_STATUS_UPDATED`")
    beacon_user_id: str = Field( description="The ID of the associated Beacon user.")
    environment: WebhookEnvironmentValues = Field()

BeaconUserStatusUpdatedWebhook.update_forward_refs()
