# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.monitoring_insights_status import MonitoringInsightsStatus
from plaid_skel.models.webhook_environment_values import WebhookEnvironmentValues




class CashFlowUpdatesLargeDepositWebhook(BaseModel):
    """For each user's item enabled for Cash Flow Updates, this webhook will fire when an update detects a deposit over $5,000. Upon receiving the webhook, call `/cra/monitoring_insights/get` to retrieve the updated insights."""


    webhook_type: str = Field( description="`CASH_FLOW_UPDATES`")
    webhook_code: str = Field( description="`LARGE_DEPOSIT_DETECTED`")
    status: MonitoringInsightsStatus = Field()
    user_id: str = Field( description="The `user_id` that the report is associated with")
    environment: WebhookEnvironmentValues = Field()

CashFlowUpdatesLargeDepositWebhook.update_forward_refs()
