# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.cashflow_report_historical_balance import CashflowReportHistoricalBalance
from plaid_skel.models.cashflow_report_monthly_summary import CashflowReportMonthlySummary




class CashflowReportAccountInsights(BaseModel):
    """Insights on the account level. These are only returned for Credit and Depository type accounts."""


    historical_balances: List[CashflowReportHistoricalBalance] = Field( description="Calculated data about the historical balances on the account.  Available for `credit` and `depository` type accounts.")
    monthly_summaries: List[CashflowReportMonthlySummary] = Field( description="Monthly summary statistics derived from transaction-level data.")

CashflowReportAccountInsights.update_forward_refs()
