# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.cause import Cause
from plaid_skel.models.check_report_warning_code import CheckReportWarningCode




class CheckReportWarning(BaseModel):
    """It is possible for a Check Report product to be returned with missing information. In such cases, the product will contain warning data in the response, indicating why obtaining the owner information failed."""


    warning_type: str = Field( description="The warning type, which will always be `CHECK_REPORT_WARNING`")
    warning_code: CheckReportWarningCode = Field()
    cause: Optional[Cause] = Field(default=None,)

CheckReportWarning.update_forward_refs()
