# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class ClientUserIdentityEmail(BaseModel):
    """User email information."""


    data: str = Field( description="User's email.")
    primary: bool = Field( description="Indicates whether this is the primary email for the User.")

ClientUserIdentityEmail.update_forward_refs()
