# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.consent_event_code import ConsentEventCode
from plaid_skel.models.consent_event_initiator import ConsentEventInitiator
from plaid_skel.models.consent_event_type import ConsentEventType
from plaid_skel.models.consented_account import ConsentedAccount




class ConsentEvent(BaseModel):
    """Describes a consent event."""


    item_id: Optional[str] = Field(default=None, description="The Plaid Item ID. The `item_id` is always unique; linking the same account at the same institution twice will result in two Items with different `item_id` values. Like all Plaid identifiers, the `item_id` is case-sensitive.")
    created_at: Optional[datetime_] = Field(default=None, description="The date and time when the consent event occurred, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.")
    event_type: Optional[ConsentEventType] = Field(default=None,)
    event_code: Optional[ConsentEventCode] = Field(default=None,)
    institution_id: Optional[str] = Field(default=None, description="Unique identifier for the institution associated with the Item. Field is `null` for Items created via Same Day Micro-deposits.")
    institution_name: Optional[str] = Field(default=None, description="The full name of the institution associated with the Item. Field is `null` for Items created via Same Day Micro-deposits.")
    initiator: Optional[ConsentEventInitiator] = Field(default=None,)
    consented_use_cases: Optional[List[str]] = Field(default=None, description="A list of strings containing the full list of use cases the end user has consented to for the Item.  See the [full list](https://plaid.com/docs/link/data-transparency-messaging-migration-guide/#updating-link-customizations) of use cases.")
    consented_data_scopes: Optional[List[str]] = Field(default=None, description="A list of strings containing the full list of data scopes the end user has consented to for the Item. These correspond to consented products; see the [full mapping](https://plaid.com/docs/link/data-transparency-messaging-migration-guide/#data-scopes-by-product) of data scopes and products.")
    consented_accounts: Optional[List[ConsentedAccount]] = Field(default=None, description="An array containing the accounts associated with the Item for which authorizations are granted.")

ConsentEvent.update_forward_refs()
