# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.counterparty_numbers_bacs import CounterpartyNumbersBACS
from plaid_skel.models.counterparty_numbers_international import CounterpartyNumbersInternational




class CounterpartyNumbers(BaseModel):
    """Account numbers associated with the counterparty, when available. This field is currently only filled in for select financial institutions in Europe."""

    model_config = ConfigDict(json_schema_extra={"nullable": True})

    bacs: Optional[CounterpartyNumbersBACS] = Field(default=None,)
    international: Optional[CounterpartyNumbersInternational] = Field(default=None,)

CounterpartyNumbers.update_forward_refs()
