# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.total_report_inflow_amount import TotalReportInflowAmount
from plaid_skel.models.total_report_outflow_amount import TotalReportOutflowAmount




class CraVoaReportAttributes(BaseModel):
    """Attributes for the VOA report."""


    total_inflow_amount: Optional[TotalReportInflowAmount] = Field(default=None,)
    total_outflow_amount: Optional[TotalReportOutflowAmount] = Field(default=None,)

CraVoaReportAttributes.update_forward_refs()
