# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class CraLoanPaymentHistory(BaseModel):
    """Contains the payment information for a loan payment period."""


    period: int = Field( description="The index to identify the loan's payment period, starting from 1. For example:   1 means the period between the loan's opening date and the 1st payment due date.   2 means the period between the loan's 1st payment due date and 2nd payment due date.")
    due_date: date_ = Field( description="The payment due date or end date of the payment period. The date should be in ISO 8601 format (YYYY-MM-DD).")
    days_past_due: int = Field( description="The number of days the loan was delinquent at the end of the pay period. If specified, should be greater of equal to 0.")
    amount_past_due: Optional[float] = Field(default=None, description="The amount past due or the charge-off amount of the loan at the end of the payment period.")
    balance_remaining: Optional[float] = Field(default=None, description="The balance remaining on the loan at the end of the payment period.")

CraLoanPaymentHistory.update_forward_refs()
