# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class CraBankIncomeIncomeProvider(BaseModel):
    """The object containing data about the income provider."""

    model_config = ConfigDict(json_schema_extra={"nullable": True})

    name: str = Field( description="The name of the income provider.")
    is_normalized: bool = Field( description="Indicates whether the income provider name is normalized by comparing it against a canonical set of known providers.")

CraBankIncomeIncomeProvider.update_forward_refs()
