# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.cra_bank_income_cause import CraBankIncomeCause
from plaid_skel.models.cra_bank_income_warning_code import CraBankIncomeWarningCode
from plaid_skel.models.credit_bank_income_warning_type import CreditBankIncomeWarningType




class CraBankIncomeWarning(BaseModel):
    """The warning associated with the data that was unavailable."""


    warning_type: Optional[CreditBankIncomeWarningType] = Field(default=None,)
    warning_code: Optional[CraBankIncomeWarningCode] = Field(default=None,)
    cause: Optional[CraBankIncomeCause] = Field(default=None,)

CraBankIncomeWarning.update_forward_refs()
