# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.plaid_lend_score_version import PlaidLendScoreVersion




class CraCheckReportLendScoreGetOptions(BaseModel):
    """Defines configuration options to generate the LendScore"""

    model_config = ConfigDict(json_schema_extra={"nullable": True})

    lend_score_version: Optional[PlaidLendScoreVersion] = Field(default=None,)

CraCheckReportLendScoreGetOptions.update_forward_refs()
