# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.products import Products
from plaid_skel.models.webhook_environment_values import WebhookEnvironmentValues




class CraUserCheckReportReadyWebhook(BaseModel):
    """Fired when the Check Report are ready to be retrieved. Once this webhook has fired, the report will be available to retrieve for 24 hours."""


    webhook_type: str = Field( description="`CHECK_REPORT`")
    webhook_code: str = Field( description="`USER_CHECK_REPORT_READY`")
    user_id: str = Field( description="The `user_id` associated with the user whose data is being requested. This is received by calling `user/create`.")
    successful_products: Optional[List[Products]] = Field(default=None, description="Specifies a list of products that have successfully been generated for the report.")
    failed_products: Optional[List[Products]] = Field(default=None, description="Specifies a list of products that have failed to generate for the report. Additional detail on what caused the failure can be found by calling the product /get endpoint.")
    item_ids: Optional[List[str]] = Field(default=None, description="A list of `item_ids` that is included in the Check Report.")
    environment: WebhookEnvironmentValues = Field()

CraUserCheckReportReadyWebhook.update_forward_refs()
