# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.cra_network_insights_item import CraNetworkInsightsItem




class CraNetworkInsightsReport(BaseModel):
    """Contains data for the CRA Network Attributes Report."""


    report_id: str = Field( description="The unique identifier associated with the report object.")
    generated_time: datetime_ = Field( description="The time when the report was generated.")
    network_attributes: Dict[str, Any] = Field( description="A map of network attributes, where the key is a string, and the value is a float, int, or boolean. For a full list of attributes, contact your account manager.")
    items: List[CraNetworkInsightsItem] = Field( description="The Items the end user connected in Link.")

CraNetworkInsightsReport.update_forward_refs()
