# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class CraBankIncomeTransaction(BaseModel):
    """The transactions data for the end user's income source(s)."""


    amount: Optional[float] = Field(default=None, description="The settled value of the transaction, denominated in the transactions's currency as stated in `iso_currency_code` or `unofficial_currency_code`. Positive values when money moves out of the account; negative values when money moves in. For example, credit card purchases are positive; credit card payment, direct deposits, and refunds are negative.")
    date: Optional[date_] = Field(default=None, description="For pending transactions, the date that the transaction occurred; for posted transactions, the date that the transaction posted. Both dates are returned in an ISO 8601 format (YYYY-MM-DD).")
    name: Optional[str] = Field(default=None, description="The merchant name or transaction description.")
    original_description: Optional[str] = Field(default=None, description="The string returned by the financial institution to describe the transaction.")
    pending: Optional[bool] = Field(default=None, description="When true, identifies the transaction as pending or unsettled. Pending transaction details (name, type, amount, category ID) may change before they are settled.")
    check_number: Optional[str] = Field(default=None, description="The check number of the transaction. This field is only populated for check transactions.")
    iso_currency_code: Optional[str] = Field(default=None, description="The ISO 4217 currency code of the amount or balance.")
    unofficial_currency_code: Optional[str] = Field(default=None, description="The unofficial currency code associated with the amount or balance. Always `null` if `iso_currency_code` is non-null. Unofficial currency codes are used for currencies that do not have official ISO currency codes, such as cryptocurrencies and the currencies of certain countries.")

CraBankIncomeTransaction.update_forward_refs()
