# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum



class CraLoanType(str, Enum):
    PERSONAL = "PERSONAL"
    CREDIT_CARD = "CREDIT_CARD"
    BUSINESS = "BUSINESS"
    MORTGAGE = "MORTGAGE"
    AUTO = "AUTO"
    PAYDAY = "PAYDAY"
    STUDENT = "STUDENT"
    HOME_EQUITY = "HOME_EQUITY"
    OTHER = "OTHER"
