# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.lend_score import LendScore




class CraLendScoreReport(BaseModel):
    """Contains data for the CRA LendScore Report."""


    report_id: str = Field( description="The unique identifier associated with the report object.")
    generated_time: datetime_ = Field( description="The time when the report was generated.")
    lend_score: Optional[LendScore] = Field(default=None,)

CraLendScoreReport.update_forward_refs()
