# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.credit_bank_income_category import CreditBankIncomeCategory




class CraMonitoringInsightsSubscribeRequest(BaseModel):
    """CraMonitoringInsightsSubscribeRequest defines the request schema for `/cra/monitoring_insights/subscribe`"""


    client_id: Optional[str] = Field(default=None, description="Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.")
    secret: Optional[str] = Field(default=None, description="Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.")
    user_id: Optional[str] = Field(default=None, description="A unique user identifier, created by `/user/create`. Integrations that began using `/user/create` after December 10, 2025 use this field to identify a user instead of the `user_token`. For more details, see [new user APIs](https://plaid.com/docs/api/users/user-apis).")
    item_id: Optional[str] = Field(default=None, description="The item ID to subscribe for Cash Flow Updates.")
    webhook: str = Field( description="URL to which Plaid will send Cash Flow Updates webhooks, for example when the requested Cash Flow Updates report is ready.")
    income_categories: Optional[List[CreditBankIncomeCategory]] = Field(default=None, description="Income categories to include in Cash Flow Updates. If empty or `null`, this field will default to including all possible categories.")
    user_token: Optional[str] = Field(default=None, description="The user token associated with the User data is being requested for. This field is used only by customers with pre-existing integrations that already use the `user_token` field. All other customers should use the `user_id` instead. For more details, see [New User APIs](https://plaid.com/docs/api/users/user-apis).")

CraMonitoringInsightsSubscribeRequest.update_forward_refs()
