# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.asset_detail import AssetDetail
from plaid_skel.models.asset_holder import AssetHolder
from plaid_skel.models.asset_holdings import AssetHoldings
from plaid_skel.models.asset_owners import AssetOwners
from plaid_skel.models.credit_freddie_mac_asset_transactions import CreditFreddieMacAssetTransactions
from plaid_skel.models.validation_sources import ValidationSources




class CreditFreddieMacAsset(BaseModel):
    """Documentation not found in the MISMO model viewer and not provided by Freddie Mac."""


    asset_detail: AssetDetail = Field()
    asset_owners: AssetOwners = Field()
    asset_holder: AssetHolder = Field()
    asset_holdings: Optional[AssetHoldings] = Field(default=None,)
    asset_transactions: CreditFreddieMacAssetTransactions = Field()
    validation_sources: ValidationSources = Field()

CreditFreddieMacAsset.update_forward_refs()
