# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.credit_freddie_mac_loans_voa24 import CreditFreddieMacLoansVOA24
from plaid_skel.models.credit_freddie_mac_parties_voa24 import CreditFreddieMacPartiesVOA24
from plaid_skel.models.credit_freddie_mac_services_voa24 import CreditFreddieMacServicesVOA24




class CreditFreddieMacVerificationOfAssetsDealVOA24(BaseModel):
    """An object representing an Asset Report with Freddie Mac schema."""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#credit_freddie_mac_verification_of_assets_deal_voa24"
            }
        }

    loans: CreditFreddieMacLoansVOA24 = Field()
    parties: CreditFreddieMacPartiesVOA24 = Field()
    services: CreditFreddieMacServicesVOA24 = Field()

CreditFreddieMacVerificationOfAssetsDealVOA24.update_forward_refs()
