# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.credit_bank_statement_upload_bank_account import CreditBankStatementUploadBankAccount
from plaid_skel.models.credit_bank_statement_upload_transaction import CreditBankStatementUploadTransaction
from plaid_skel.models.credit_document_metadata import CreditDocumentMetadata




class CreditBankStatementUploadObject(BaseModel):
    """An object containing data that has been parsed from a user-uploaded bank statement."""


    transactions: List[CreditBankStatementUploadTransaction] = Field( description="An array of transactions appearing on the bank statement.")
    document_metadata: CreditDocumentMetadata = Field()
    document_id: Optional[str] = Field(default=None, description="An identifier of the document referenced by the document metadata.")
    bank_accounts: List[CreditBankStatementUploadBankAccount] = Field( description="An array of bank accounts associated with the uploaded bank statement.")

CreditBankStatementUploadObject.update_forward_refs()
