# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.credit_freddie_verification_of_employment_deal_voe25 import CreditFreddieVerificationOfEmploymentDealVOE25




class CreditFreddieVerificationOfEmploymentVOE25(BaseModel):
    """Verification of Employment Report"""

    model_config = ConfigDict(json_schema_extra={"nullable": True})

    deal: CreditFreddieVerificationOfEmploymentDealVOE25 = Field()
    schema_version: float = Field( description="The Verification Of Employment (VOE) schema version.")

CreditFreddieVerificationOfEmploymentVOE25.update_forward_refs()
