# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.credit_freddie_mac_service import CreditFreddieMacService




class CreditFreddieMacServices(BaseModel):
    """A collection of objects that describe requests and responses for services."""


    service: CreditFreddieMacService = Field()

CreditFreddieMacServices.update_forward_refs()
