# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.payroll_item import PayrollItem
from plaid_skel.models.plaid_error import PlaidError




class CreditPayrollIncomeGetResponse(BaseModel):
    """Defines the response body for `/credit/payroll_income/get`."""


    items: List[PayrollItem] = Field( description="Array of payroll items.")
    error: Optional[PlaidError] = Field(default=None,)
    request_id: str = Field( description="A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.")

CreditPayrollIncomeGetResponse.update_forward_refs()
