# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum



class CreditPayStubPayBasisType(str, Enum):
    SALARY = "SALARY"
    HOURLY = "HOURLY"
    COMMISSION = "COMMISSION"
