# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class CreditFreddieMacIndividualNameVOA24(BaseModel):
    """Documentation not found in the MISMO model viewer and not provided by Freddie Mac."""


    first_name: str = Field( description="The first name of the individual represented by the parent object.")
    last_name: str = Field( description="The last name of the individual represented by the parent object.")
    middle_name: str = Field( description="The middle name of the individual represented by the parent object.")

CreditFreddieMacIndividualNameVOA24.update_forward_refs()
