# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.report_type import ReportType




class CreditRelayRefreshRequest(BaseModel):
    """CreditRelayRefreshRequest defines the request schema for `/credit/relay/refresh`"""


    client_id: Optional[str] = Field(default=None, description="Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.")
    secret: Optional[str] = Field(default=None, description="Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.")
    relay_token: str = Field( description="The `relay_token` granting access to the report you would like to refresh.")
    report_type: ReportType = Field()
    webhook: Optional[str] = Field(default=None, description="The URL registered to receive webhooks when the report of a relay token has been refreshed.")

CreditRelayRefreshRequest.update_forward_refs()
