# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum


class CreditBankEmploymentWarningType(str, Enum):
    BANK_EMPLOYMENT_WARNING = "BANK_EMPLOYMENT_WARNING"
