# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.credit_pay_stub_address import CreditPayStubAddress




class Credit1099Recipient(BaseModel):
    """An object representing a recipient used in both 1099-K and 1099-MISC tax documents."""


    address: Optional[CreditPayStubAddress] = Field(default=None,)
    name: Optional[str] = Field(default=None, description="Name of recipient.")
    tin: Optional[str] = Field(default=None, description="Tax identification number of recipient.")
    account_number: Optional[str] = Field(default=None, description="Account number number of recipient.")
    facta_filing_requirement: Optional[str] = Field(default=None, description="Checked if FACTA is a filing requirement.")
    second_tin_exists: Optional[str] = Field(default=None, description="Checked if 2nd TIN exists.")

Credit1099Recipient.update_forward_refs()
