# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.credit_freddie_mac_loans_voa24 import CreditFreddieMacLoansVOA24
from plaid_skel.models.credit_freddie_mac_parties_voa24 import CreditFreddieMacPartiesVOA24
from plaid_skel.models.credit_freddie_mac_services_voe25 import CreditFreddieMacServicesVOE25




class CreditFreddieVerificationOfEmploymentDealVOE25(BaseModel):
    """An object representing a Verification of Employment report."""


    loans: CreditFreddieMacLoansVOA24 = Field()
    parties: CreditFreddieMacPartiesVOA24 = Field()
    services: CreditFreddieMacServicesVOE25 = Field()

CreditFreddieVerificationOfEmploymentDealVOE25.update_forward_refs()
