# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class DepositSwitchTokenCreateResponse(BaseModel):
    """DepositSwitchTokenCreateResponse defines the response schema for `/deposit_switch/token/create`"""


    deposit_switch_token: str = Field( description="Deposit switch token, used to initialize Link for the Deposit Switch product")
    deposit_switch_token_expiration_time: str = Field( description="Expiration time of the token, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format")
    request_id: str = Field( description="A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.")

DepositSwitchTokenCreateResponse.update_forward_refs()
