# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum



class DocumentDateOfBirthMatchCode(str, Enum):
    MATCH = "match"
    PARTIAL_MATCH = "partial_match"
    NO_MATCH = "no_match"
