# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from strenum import StrEnum

DocumentAuthenticityMatchCode = StrEnum("DocumentAuthenticityMatchCode", names=['match', 'partial_match', 'no_match', 'no_data'])