# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum


class EarningsBreakdownCanonicalDescription(str, Enum):
    BONUS = "BONUS"
    COMMISSION = "COMMISSION"
    OVERTIME = "OVERTIME"
    PAID_TIME_OFF = "PAID TIME OFF"
    REGULAR_PAY = "REGULAR PAY"
    VACATION = "VACATION"
    BASIC_ALLOWANCE_HOUSING = "BASIC ALLOWANCE HOUSING"
    BASIC_ALLOWANCE_SUBSISTENCE = "BASIC ALLOWANCE SUBSISTENCE"
    OTHER = "OTHER"

# Nullable OpenAPI enum
    @classmethod
    def __get_pydantic_json_schema__(cls, field_schema: dict) -> None:
        field_schema["nullable"] = True
