# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from strenum import StrEnum

EmploymentVerificationStatus = StrEnum("EmploymentVerificationStatus", names=['EMPLOYMENT_STATUS_ACTIVE', 'EMPLOYMENT_STATUS_INACTIVE'])