# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.employer_verification import EmployerVerification
from plaid_skel.models.employment_verification_status import EmploymentVerificationStatus
from plaid_skel.models.platform_ids import PlatformIds




class EmploymentVerification(BaseModel):
    """An object containing proof of employment data for an individual"""


    status: Optional[EmploymentVerificationStatus] = Field(default=None,)
    start_date: Optional[date] = Field(default=None, description="Start of employment in ISO 8601 format (YYYY-MM-DD).")
    end_date: Optional[date] = Field(default=None, description="End of employment, if applicable. Provided in ISO 8601 format (YYY-MM-DD).")
    employer: Optional[EmployerVerification] = Field(default=None,)
    title: Optional[str] = Field(default=None, description="Current title of employee.")
    platform_ids: Optional[PlatformIds] = Field(default=None,)

EmploymentVerification.update_forward_refs()
