# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.entity_screening_hit_phone_numbers import EntityScreeningHitPhoneNumbers
from plaid_skel.models.match_summary import MatchSummary




class EntityScreeningHitsPhoneNumberItems(BaseModel):
    """Analyzed phone numbers for the associated hit"""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#entity_screening_hits_phone_number_items"
            }
        }

    analysis: Optional[MatchSummary] = Field(default=None,)
    data: Optional[EntityScreeningHitPhoneNumbers] = Field(default=None,)

EntityScreeningHitsPhoneNumberItems.update_forward_refs()
