# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from strenum import StrEnum

EntityDocumentType = StrEnum("EntityDocumentType", names=['bik', 'business_number', 'imo', 'other', 'swift', 'tax_id'])