# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.entity_screening_hit_urls import EntityScreeningHitUrls
from plaid_skel.models.match_summary import MatchSummary




class EntityScreeningHitUrlsItems(BaseModel):
    """Analyzed URLs for the associated hit"""


    analysis: Optional[MatchSummary] = Field(default=None,)
    data: Optional[EntityScreeningHitUrls] = Field(default=None,)

EntityScreeningHitUrlsItems.update_forward_refs()
