# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class EwaScore(BaseModel):
    """EwaScore represents an earned wage access score for a specific advance amount range."""


    lowest_amount: Optional[float] = Field(default=None, description="Float value representing the lower bound (inclusive) of the advance amount range associated with a specific EWA score.")
    highest_amount: Optional[float] = Field(default=None, description="Float value representing the upper bound (exclusive) of the advance amount range associated with a specific EWA score.")
    score: Optional[int] = Field(default=None, description="EWA score for the corresponding amount bucket. Scores range from 1-99, where a higher score indicates a higher likelihood of repayment.")

EwaScore.update_forward_refs()
