# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum



class FDXNotificationSeverity(str, Enum):
    EMERGENCY = "EMERGENCY"
    ALERT = "ALERT"
    WARNING = "WARNING"
    NOTICE = "NOTICE"
    INFO = "INFO"
