# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum


class FDXContentTypes(str, Enum):
    APPLICATION_PDF = "application/pdf"
    IMAGE_GIF = "image/gif"
    IMAGE_JPEG = "image/jpeg"
    IMAGE_TIFF = "image/tiff"
    IMAGE_PNG = "image/png"
    APPLICATION_JSON = "application/json"
