# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.fdx_recipient_metadata import FDXRecipientMetadata




class GetRecipientResponse(BaseModel):
    """GetRecipientResponse defines the response schema for `/fdx/recipient/{recipientId}`"""


    recipient_id: str = Field( description="The recipient identifier")
    client_name: str = Field( description="The recipient name displayed by the Data Provider during the consent flow")
    logo_uri: Optional[str] = Field(default=None, description="Data Recipient Logo URL location")
    third_party_legal_name: str = Field( description="The legal name of the recipient")

    @field_validator("recipient_id")
    @classmethod
    def recipient_id_max_length(cls, value):
        assert len(value) <= 256
        return value

    @field_validator("client_name")
    @classmethod
    def client_name_max_length(cls, value):
        assert len(value) <= 256
        return value

    @field_validator("third_party_legal_name")
    @classmethod
    def third_party_legal_name_max_length(cls, value):
        assert len(value) <= 256
        return value

GetRecipientResponse.update_forward_refs()
