# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class HistoricalAnnualIncome(BaseModel):
    """An object representing the historical annual income amount."""


    baseline_amount: Optional[float] = Field(default=None, description="The historical annual income at the time of subscription")
    current_amount: float = Field( description="The current historical annual income")

HistoricalAnnualIncome.update_forward_refs()
