# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum



class IdentityUpdateTypes(str, Enum):
    PHONES = "PHONES"
    ADDRESSES = "ADDRESSES"
    EMAILS = "EMAILS"
    NAMES = "NAMES"
