# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class IdentityVerificationDocumentNameResponse(BaseModel):
    """The individual's name extracted from the document."""

    model_config = ConfigDict(json_schema_extra={"nullable": True})

    given_name: str = Field( description="A string with at least one non-whitespace character, with a max length of 100 characters.")
    family_name: str = Field( description="A string with at least one non-whitespace character, with a max length of 100 characters.")

IdentityVerificationDocumentNameResponse.update_forward_refs()
