# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.identity_document_upload_metadata import IdentityDocumentUploadMetadata
from plaid_skel.models.identity_document_upload_risk_insights import IdentityDocumentUploadRiskInsights




class IdentityDocumentUpload(BaseModel):
    """Document object with metadata of the uploaded document"""


    document_id: Optional[str] = Field(default=None, description="A UUID identifying the document.")
    metadata: Optional[IdentityDocumentUploadMetadata] = Field(default=None,)
    risk_insights: Optional[IdentityDocumentUploadRiskInsights] = Field(default=None,)

IdentityDocumentUpload.update_forward_refs()
