# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.beacon_user_id_nullable import BeaconUserIDNullable
from plaid_skel.models.documentary_verification import DocumentaryVerification
from plaid_skel.models.idv_protect_event import IDVProtectEvent
from plaid_skel.models.identity_verification_status import IdentityVerificationStatus
from plaid_skel.models.identity_verification_step_summary import IdentityVerificationStepSummary
from plaid_skel.models.identity_verification_template_reference import IdentityVerificationTemplateReference
from plaid_skel.models.identity_verification_user_data import IdentityVerificationUserData
from plaid_skel.models.kyc_check_details import KYCCheckDetails
from plaid_skel.models.risk_check_details import RiskCheckDetails
from plaid_skel.models.selfie_check import SelfieCheck
from plaid_skel.models.verify_sms_details import VerifySMSDetails
from plaid_skel.models.watchlist_screening_individual_id_nullable import WatchlistScreeningIndividualIDNullable




class IdentityVerification(BaseModel):
    """A identity verification attempt represents a customer's attempt to verify their identity, reflecting the required steps for completing the session, the results for each step, and information collected in the process."""


    id: str = Field( description="ID of the associated Identity Verification attempt.")
    client_user_id: str = Field( description="A unique ID that identifies the end user in your system. Either a `user_id` or the `client_user_id` must be provided. This ID can also be used to associate user-specific data from other Plaid products. Financial Account Matching requires this field and the `/link/token/create` `client_user_id` to be consistent. Personally identifiable information, such as an email address or phone number, should not be used in the `client_user_id`.")
    created_at: datetime_ = Field( description="An ISO8601 formatted timestamp.")
    completed_at: Optional[datetime_] = Field(default=None, description="An ISO8601 formatted timestamp.")
    previous_attempt_id: Optional[str] = Field(default=None, description="The ID for the Identity Verification preceding this session. This field will only be filled if the current Identity Verification is a retry of a previous attempt.")
    shareable_url: Optional[str] = Field(default=None, description="A shareable URL that can be sent directly to the user to complete verification")
    template: IdentityVerificationTemplateReference = Field()
    user: IdentityVerificationUserData = Field()
    status: IdentityVerificationStatus = Field()
    steps: IdentityVerificationStepSummary = Field()
    documentary_verification: Optional[DocumentaryVerification] = Field(default=None,)
    selfie_check: SelfieCheck = Field()
    kyc_check: KYCCheckDetails = Field()
    risk_check: RiskCheckDetails = Field()
    verify_sms: Optional[VerifySMSDetails] = Field(default=None,)
    watchlist_screening_id: WatchlistScreeningIndividualIDNullable = Field()
    beacon_user_id: BeaconUserIDNullable = Field()
    user_id: Optional[str] = Field(default=None, description="Unique user identifier, created by calling `/user/create`. Either a `user_id` or the `client_user_id` must be provided. The `user_id` may only be used instead of the `client_user_id` if you were not a pre-existing user of `/user/create` as of December 10, 2025; for more details, see [New User APIs](https://plaid.com/docs/api/users/user-apis). If both this field and a `client_user_id` are present in a request, the `user_id` must have been created from the provided `client_user_id`.")
    redacted_at: Optional[datetime_] = Field(default=None, description="An ISO8601 formatted timestamp.")
    latest_scored_protect_event: Optional[IDVProtectEvent] = Field(default=None,)

IdentityVerification.update_forward_refs()
