# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class IdentityVerificationTemplateReference(BaseModel):
    """The resource ID and version number of the template configuring the behavior of a given Identity Verification."""


    id: str = Field( description="ID of the associated Identity Verification template. Like all Plaid identifiers, this is case-sensitive.")
    version: int = Field( description="Version of the associated Identity Verification template.")

IdentityVerificationTemplateReference.update_forward_refs()
