# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.account_identity_match_score import AccountIdentityMatchScore
from plaid_skel.models.item import Item




class IdentityMatchResponse(BaseModel):
    """IdentityMatchResponse defines the response schema for `/identity/match`"""


    accounts: List[AccountIdentityMatchScore] = Field( description="The accounts for which Identity match has been requested")
    item: Item = Field()
    request_id: str = Field( description="A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.")

IdentityMatchResponse.update_forward_refs()
