# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum

from pydantic import GetJsonSchemaHandler
from pydantic.json_schema import JsonSchemaValue


class IdentityUpdateTypes(str, Enum):
    PHONES = "PHONES"
    ADDRESSES = "ADDRESSES"
    EMAILS = "EMAILS"
    NAMES = "NAMES"
