# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.verification_status import VerificationStatus




class IncomeSummaryFieldNumber(BaseModel):
    """Field number for income summary"""


    value: float = Field( description="The value of the field.")
    verification_status: VerificationStatus = Field()

IncomeSummaryFieldNumber.update_forward_refs()
