# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class IncomeInsightsTotalIncome(BaseModel):
    """The total amount of all income transactions in the given time period."""


    amount: Optional[float] = Field(default=None, description="If the parent object represents a category of transactions, such as `total_amount`, `transfers_in`, `total_income`, etc. the `amount` represents the sum of all of the transactions in the group.   If the parent object is `cash_flow`, the `amount` represents the total value of all the inflows minus all the outflows across all the accounts in the report in the given time window.   If the parent object is `minimum_balance`, the `amount` represents the lowest balance of the account during the given time window.")
    iso_currency_code: Optional[str] = Field(default=None, description="The ISO-4217 currency code of the amount. Always `null` if `unofficial_currency_code` is non-`null`.")
    unofficial_currency_code: Optional[str] = Field(default=None, description="The unofficial currency code associated with the amount. Always `null` if `iso_currency_code` is non-`null`.  See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `unofficial_currency_code`s.")

IncomeInsightsTotalIncome.update_forward_refs()
