# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.income_verification_precheck_employer_address import IncomeVerificationPrecheckEmployerAddress




class IncomeVerificationPrecheckEmployer(BaseModel):
    """Information about the end user's employer"""

    class Config:
        schema_extra = {"nullable": True}

    name: Optional[str] = Field(default=None, description="The employer's name")
    address: Optional[IncomeVerificationPrecheckEmployerAddress] = Field(default=None,)
    tax_id: Optional[str] = Field(default=None, description="The employer's tax id")
    url: Optional[str] = Field(default=None, description="The URL for the employer's public website")

IncomeVerificationPrecheckEmployer.update_forward_refs()
