# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.income_verification_precheck_confidence import IncomeVerificationPrecheckConfidence




class IncomeVerificationPrecheckResponse(BaseModel):
    """IncomeVerificationPrecheckResponse defines the response schema for `/income/verification/precheck`."""


    precheck_id: str = Field( description="ID of the precheck. Provide this value when calling `/link/token/create` in order to optimize Link conversion.")
    request_id: str = Field( description="A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.")
    confidence: IncomeVerificationPrecheckConfidence = Field()

IncomeVerificationPrecheckResponse.update_forward_refs()
