# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class InstitutionsGetByIdRequestOptions(BaseModel):
    """Specifies optional parameters for `/institutions/get_by_id`. If provided, must not be `null`."""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#institutions_get_by_id_request_options"
            }
        }

    include_optional_metadata: Optional[bool] = Field(default=None, description="When `true`, return an institution's logo, brand color, and URL. When available, the bank's logo is returned as a base64 encoded 152x152 PNG, the brand color is in hexadecimal format. The default value is `false`.  Note that Plaid does not own any of the logos shared by the API and that by accessing or using these logos, you agree that you are doing so at your own risk and will, if necessary, obtain all required permissions from the appropriate rights holders and adhere to any applicable usage guidelines. Plaid disclaims all express or implied warranties with respect to the logos.")
    include_status: Optional[bool] = Field(default=None, description="If `true`, the response will include status information about the institution. Default value is `false`.")
    include_auth_metadata: Optional[bool] = Field(default=None, description="When `true`, returns metadata related to the Auth product indicating which auth methods are supported.")
    include_payment_initiation_metadata: Optional[bool] = Field(default=None, description="When `true`, returns metadata related to the Payment Initiation product indicating which payment configurations are supported.")

InstitutionsGetByIdRequestOptions.update_forward_refs()
