# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.country_code import CountryCode




class Institution(BaseModel):
    """Details relating to a specific financial institution"""


    institution_id: str = Field( description="Unique identifier for the institution")
    name: str = Field( description="The official name of the institution")
    country_codes: List[CountryCode] = Field( description="A list of the country codes supported by the institution.")
    url: Optional[str] = Field(default=None, description="The URL for the institution's website")
    primary_color: Optional[str] = Field(default=None, description="Hexadecimal representation of the primary color used by the institution")

Institution.update_forward_refs()
