# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.numbers_acats import NumbersACATS
from plaid_skel.models.numbers_aton import NumbersATON




class InvestmentsAuthGetNumbers(BaseModel):
    """Identifying information for transferring holdings to an investments account."""


    acats: Optional[List[NumbersACATS]] = Field(default=None,)
    aton: Optional[List[NumbersATON]] = Field(default=None,)

InvestmentsAuthGetNumbers.update_forward_refs()
