# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum



class IssuesStatus(str, Enum):
    REPORTED = "REPORTED"
    AWAITING_RESOLUTION = "AWAITING_RESOLUTION"
    FIX_IN_PROGRESS = "FIX_IN_PROGRESS"
    FIX_PENDING_VALIDATION = "FIX_PENDING_VALIDATION"
    CANNOT_FIX = "CANNOT_FIX"
    RESOLVED = "RESOLVED"
