# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum


from pydantic import GetJsonSchemaHandler
from pydantic.json_schema import JsonSchemaValue



class ItemAuthMethod(str, Enum):
    INSTANT_AUTH = "INSTANT_AUTH"
    INSTANT_MATCH = "INSTANT_MATCH"
    AUTOMATED_MICRODEPOSITS = "AUTOMATED_MICRODEPOSITS"
    SAME_DAY_MICRODEPOSITS = "SAME_DAY_MICRODEPOSITS"
    INSTANT_MICRODEPOSITS = "INSTANT_MICRODEPOSITS"
    DATABASE_MATCH = "DATABASE_MATCH"
    DATABASE_INSIGHTS = "DATABASE_INSIGHTS"
    TRANSFER_MIGRATED = "TRANSFER_MIGRATED"
    INVESTMENTS_FALLBACK = "INVESTMENTS_FALLBACK"

# Nullable OpenAPI enum
@classmethod
def __get_pydantic_json_schema__(cls, field_schema: dict, handler: GetJsonSchemaHandler) -> JsonSchemaValue:
    schema = handler(field_schema)
    schema["nullable"] = True
    return schema
