# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.item_auth_method import ItemAuthMethod
from plaid_skel.models.plaid_error import PlaidError
from plaid_skel.models.products import Products




class Item(BaseModel):
    """Metadata about the Item."""


    item_id: str = Field( description="The Plaid Item ID. The `item_id` is always unique; linking the same account at the same institution twice will result in two Items with different `item_id` values. Like all Plaid identifiers, the `item_id` is case-sensitive.")
    institution_id: Optional[str] = Field(default=None, description="The Plaid Institution ID associated with the Item. Field is `null` for Items created without an institution connection, such as Items created via Same Day Micro-deposits.")
    institution_name: Optional[str] = Field(default=None, description="The name of the institution associated with the Item. Field is `null` for Items created without an institution connection, such as Items created via Same Day Micro-deposits.")
    webhook: Optional[str] = Field(default=None, description="The URL registered to receive webhooks for the Item.")
    auth_method: Optional[ItemAuthMethod] = Field(default=None,)
    error: Optional[PlaidError] = Field(default=None,)
    available_products: List[Products] = Field( description="A list of products available for the Item that have not yet been accessed. The contents of this array will be mutually exclusive with `billed_products`.")
    billed_products: List[Products] = Field( description="A list of products that have been billed for the Item. The contents of this array will be mutually exclusive with `available_products`. Note - `billed_products` is populated in all environments but only requests in Production are billed. Also note that products that are billed on a pay-per-call basis rather than a pay-per-Item basis, such as `balance`, will not appear here. ")
    products: Optional[List[Products]] = Field(default=None, description="A list of products added to the Item. In almost all cases, this will be the same as the `billed_products` field. For some products, it is possible for the product to be added to an Item but not yet billed (e.g. Assets, before `/asset_report/create` has been called, or Auth or Identity when added as Optional Products but before their endpoints have been called), in which case the product may appear in `products` but not in `billed_products`. ")
    consented_products: Optional[List[Products]] = Field(default=None, description="A list of products that the user has consented to for the Item via [Data Transparency Messaging](https://plaid.com/docs/link/data-transparency-messaging-migration-guide). This will consist of all products where both of the following are true: the user has consented to the required data scopes for that product and you have Production access for that product. ")

Item.update_forward_refs()
