# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class ItemImportRequestOptions(BaseModel):
    """An optional object to configure `/item/import` request."""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#item_import_request_options"
            }
        }

    webhook: Optional[str] = Field(default=None, description="Specifies a webhook URL to associate with an Item. Plaid fires a webhook if credentials fail. ")

ItemImportRequestOptions.update_forward_refs()
