# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.webhook_environment_values import WebhookEnvironmentValues




class LayerAuthenticationPassedWebhook(BaseModel):
    """Indicates that Plaid's authentication process has completed for a user and that Plaid has verified that the user owns their phone number. If you receive this webhook, you should skip your own OTP phone number verification flow for the user, even if the user does not complete the entire Link flow. If the user doesn't complete the full Link flow (as verified by your being able to successfully call `/user_account/session/get` using the `public_token` from the `onSuccess` callback) it is recommended that you implement [webhook verification](https://plaid.com/docs/api/webhooks/webhook-verification/) or another technique to avoid webhook spoofing attacks."""


    webhook_type: str = Field( description="`LAYER`")
    webhook_code: str = Field( description="`LAYER_AUTHENTICATION_PASSED`")
    environment: WebhookEnvironmentValues = Field()
    link_session_id: str = Field( description="An identifier for the Link session these events occurred in")
    link_token: str = Field( description="The Link token used to create the Link session these events are from")

LayerAuthenticationPassedWebhook.update_forward_refs()
