# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class LinkTokenCreateRequestAuth(BaseModel):
    """Specifies options for initializing Link for use with the Auth product. This field can be used to enable or disable extended Auth flows for the resulting Link session. Omitting any field will result in a default that can be configured by your account manager."""


    auth_type_select_enabled: Optional[bool] = Field(default=None, description="Specifies whether Auth Type Select is enabled for the Link session, allowing the end user to choose between linking instantly or manually prior to selecting their financial institution. Note that this can only be true if `same_day_microdeposits_enabled` is set to true.")
    automated_microdeposits_enabled: Optional[bool] = Field(default=None, description="Specifies whether the Link session is enabled for the Automated Micro-deposits flow.")
    instant_match_enabled: Optional[bool] = Field(default=None, description="Specifies whether the Link session is enabled for the Instant Match flow. As of November 2022, Instant Match will be enabled by default. Instant Match can be disabled by setting this field to `false`.")
    same_day_microdeposits_enabled: Optional[bool] = Field(default=None, description="Specifies whether the Link session is enabled for the Same Day Micro-deposits flow.")
    reroute_to_credentials: Optional[str] = Field(default=None, description="Specifies what type of [Reroute to Credentials](https://plaid.com/docs/auth/coverage/same-day/#reroute-to-credentials) pane should be used in the Link session for the Same Day Micro-deposits flow. As of October 15 2023, the default setting is `OPTIONAL`.")
    flow_type: Optional[str] = Field(default=None, description="This field has been deprecated in favor of `auth_type_select_enabled`.")

LinkTokenCreateRequestAuth.update_forward_refs()
