# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class LinkSessionExitMetadataInstitution(BaseModel):
    """An institution object. If the Item was created via Same-Day or Instant micro-deposit verification, will be `null`."""

    model_config = ConfigDict(json_schema_extra={"nullable": True})

    name: Optional[str] = Field(default=None, description="The full institution name, such as `Wells Fargo`")
    institution_id: Optional[str] = Field(default=None, description="The Plaid institution identifier")

LinkSessionExitMetadataInstitution.update_forward_refs()
