# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.network_insights_version import NetworkInsightsVersion




class LinkTokenCreateRequestCraOptionsNetworkInsights(BaseModel):
    """Specifies options for initializing Link for use with the CRA Network Insights product."""


    network_insights_version: Optional[NetworkInsightsVersion] = Field(default=None,)

LinkTokenCreateRequestCraOptionsNetworkInsights.update_forward_refs()
