# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.link_event import LinkEvent




class LinkEventsWebhook(BaseModel):
    """Contains a summary of the events from a link session"""


    webhook_type: str = Field( description="`LINK`")
    webhook_code: str = Field( description="`EVENTS`")
    events: List[LinkEvent] = Field( description="The link events emitted during the link session")
    link_session_id: str = Field( description="An identifier for the link session these events occurred in")
    link_token: str = Field( description="The link token used to create the link session these events are from")

LinkEventsWebhook.update_forward_refs()
