# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.income_verification_doc_parsing_config import IncomeVerificationDocParsingConfig




class LinkTokenCreateIdentity(BaseModel):
    """Identity object used to specify document upload"""


    is_document_upload: Optional[bool] = Field(default=None, description="Used to specify whether the Link session is Identity Document Upload")
    account_ids: Optional[List[str]] = Field(default=None, description="An array of `account_ids`. Currently can only contain one `account_id`. Must be populated if using Document Upload.")
    parsing_configs: Optional[List[IncomeVerificationDocParsingConfig]] = Field(default=None, description="An array of parsing configurations. Valid parsing configurations are `ocr` and `risk_signals`. If parsing configurations are omitted, defaults to `ocr`")

LinkTokenCreateIdentity.update_forward_refs()
