# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.prism_product import PrismProduct




class LinkTokenCreateRequestCreditPartnerInsights(BaseModel):
    """Specifies options for initializing Link for use with the Credit Partner Insights product."""


    days_requested: Optional[int] = Field(default=None, description="The maximum integer number of days of history to compute Credit Partner Insights. Defaults to 180 if not specified")
    prism_products: Optional[List[PrismProduct]] = Field(default=None, description="The specific Prism products to return. If none are passed in, then all products will be returned.")

    @field_validator("days_requested")
    @classmethod
    def days_requested_max(cls, value):
        assert value <= 730
        return value

    @field_validator("days_requested")
    @classmethod
    def days_requested_min(cls, value):
        assert value >= 1
        return value

LinkTokenCreateRequestCreditPartnerInsights.update_forward_refs()
