# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class LinkTokenCreateRequestUpdate(BaseModel):
    """Specifies options for initializing Link for [update mode](https://plaid.com/docs/link/update-mode)."""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#link_token_create_request_update"
            }
        }

    account_selection_enabled: Optional[bool] = Field(default=None, description="If `true`, enables [update mode with Account Select](https://plaid.com/docs/link/update-mode/#using-update-mode-to-request-new-accounts).")

LinkTokenCreateRequestUpdate.update_forward_refs()
