# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from strenum import StrEnum

LinkDeliverySessionStatus = StrEnum("LinkDeliverySessionStatus", names=['CREATED', 'OPENED', 'COMPLETED', 'EXPIRED'])