# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class LinkTokenEUConfig(BaseModel):
    """Configuration parameters for EU flows"""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#link_token_eu_config"
            }
        }

    headless: Optional[bool] = Field(default=None, description="If `true`, open Link without an initial UI. Defaults to `false`.")

LinkTokenEUConfig.update_forward_refs()
