# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class LinkDeliveryInstitution(BaseModel):
    """Information related to the financial institution."""


    name: Optional[str] = Field(default=None, description="The full institution name, such as 'Wells Fargo'")
    institution_id: Optional[str] = Field(default=None, description="The Plaid institution identifier")

LinkDeliveryInstitution.update_forward_refs()
