# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class LinkTokenCreateRequestIdentityVerification(BaseModel):
    """Specifies option for initializing Link for use with the Identity Verification product."""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#link_token_create_request_identity_verification"
            }
        }

    template_id: str = Field( description="ID of the associated Identity Verification template.")
    consent: Optional[bool] = Field(default=None,)
    gave_consent: Optional[bool] = Field(default=None, description="A flag specifying whether the end user has already agreed to a privacy policy specifying that their data will be shared with Plaid for verification purposes.  If `gave_consent` is set to `true`, the `accept_tos` step will be marked as `skipped` and the end user's session will start at the next step requirement.")

LinkTokenCreateRequestIdentityVerification.update_forward_refs()
