# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.webhook_environment_values import WebhookEnvironmentValues




class LinkSessionFinishedWebhook(BaseModel):
    """Contains the state of a completed Link session, along with the public token(s) if available.  By default, this webhook is sent only for sessions enabled for the Hosted Link flow (including Link Recovery flows), a Multi-Item Link flow, or a Layer flow. If you would like to receive this webhook for other sessions, contact your Account Manager or Support. This enablement will also enable the `EVENTS` webhook for all Link sessions and the ability to use `/link/token/get` to retrieve events for non-Hosted-Link sessions."""


    webhook_type: str = Field( description="`LINK`")
    webhook_code: str = Field( description="`SESSION_FINISHED`")
    status: str = Field( description="The final status of the Link session. Will always be \"SUCCESS\" or \"EXITED\".")
    link_session_id: str = Field( description="The identifier for the Link session.")
    link_token: str = Field( description="The link token used to create the Link session.")
    public_token: Optional[str] = Field(default=None, description="The public token generated by the Link session. This field has been deprecated; please use `public_tokens` instead.")
    public_tokens: Optional[List[str]] = Field(default=None, description="The public tokens generated by the Link session.")
    environment: WebhookEnvironmentValues = Field()

LinkSessionFinishedWebhook.update_forward_refs()
