# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from strenum import StrEnum

LoanAccountSubtype = StrEnum("LoanAccountSubtype", names=['auto', 'business', 'commercial', 'construction', 'consumer', 'home equity', 'loan', 'mortgage', 'line of credit', 'student', 'other', 'all'])