# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class MerchantInsights(BaseModel):
    """Insights into a user’s top merchants."""


    name: str = Field( description="The counterparty name.")
    entity_id: Optional[str] = Field(default=None, description="A unique, stable, Plaid-generated id that maps to the merchant.")
    website: Optional[str] = Field(default=None, description="The website associated with the merchant.")
    transaction_count: int = Field( description="The number of transactions associated with merchant of this type.")
    personal_finance_category_primary: Optional[str] = Field(default=None, description="The primary personal finance category associated with this merchant.")
    personal_finance_category_detailed: Optional[str] = Field(default=None, description="The detailed personal finance category associated with this merchant.")
    total_outflows: float = Field( description="Sum of outflow amounts.")
    total_inflows: float = Field( description="Sum of inflow amounts.")

MerchantInsights.update_forward_refs()
