# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class MonthlyAverage(BaseModel):
    """The monthly average amount calculated by dividing the total by the number of calendar months in the time period."""

    model_config = ConfigDict(json_schema_extra={"nullable": True})

    amount: Optional[float] = Field(default=None, description="The monthly average amount of all the aggregated transactions of the given category, across all the accounts for the given time window.  The average is calculated by dividing the total amount of the transactions by the number of calendar months in the given time window.")
    iso_currency_code: Optional[str] = Field(default=None, description="The ISO-4217 currency code of the amount. Always `null` if `unofficial_currency_code` is non-`null`.")
    unofficial_currency_code: Optional[str] = Field(default=None, description="The unofficial currency code associated with the amount. Always `null` if `iso_currency_code` is non-`null`.  See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `unofficial_currency_code`s.")

MonthlyAverage.update_forward_refs()
