# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.amount_with_currency import AmountWithCurrency




class MonthlySummary(BaseModel):
    """Monthly summary of transactions within a specific time period, showing aggregated amounts."""

    model_config = ConfigDict(json_schema_extra={"nullable": True})

    start_date: Optional[date_] = Field(default=None, description="The start date of the month for the given report time window. Will be provided in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).")
    end_date: Optional[date_] = Field(default=None, description="The end date of the month for the given report time window. Will be provided in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).")
    total_amount: Optional[AmountWithCurrency] = Field(default=None,)

MonthlySummary.update_forward_refs()
