# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.mortgage_interest_rate import MortgageInterestRate
from plaid_skel.models.mortgage_property_address import MortgagePropertyAddress




class MortgageLiability(BaseModel):
    """Contains details about a mortgage account."""


    account_id: str = Field( description="The ID of the account that this liability belongs to.")
    account_number: str = Field( description="The account number of the loan.")
    current_late_fee: Optional[float] = Field(default=None, description="The current outstanding amount charged for late payment.")
    escrow_balance: Optional[float] = Field(default=None, description="Total amount held in escrow to pay taxes and insurance on behalf of the borrower.")
    has_pmi: Optional[bool] = Field(default=None, description="Indicates whether the borrower has private mortgage insurance in effect.")
    has_prepayment_penalty: Optional[bool] = Field(default=None, description="Indicates whether the borrower will pay a penalty for early payoff of mortgage.")
    interest_rate: MortgageInterestRate = Field()
    last_payment_amount: Optional[float] = Field(default=None, description="The amount of the last payment.")
    last_payment_date: Optional[date_] = Field(default=None, description="The date of the last payment. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).")
    loan_type_description: Optional[str] = Field(default=None, description="Description of the type of loan, for example `conventional`, `fixed`, or `variable`. This field is provided directly from the loan servicer and does not have an enumerated set of possible values.")
    loan_term: Optional[str] = Field(default=None, description="Full duration of mortgage as at origination (e.g. `10 year`).")
    maturity_date: Optional[date_] = Field(default=None, description="Original date on which mortgage is due in full. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).")
    next_monthly_payment: Optional[float] = Field(default=None, description="The amount of the next payment.")
    next_payment_due_date: Optional[date_] = Field(default=None, description="The due date for the next payment. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).")
    origination_date: Optional[date_] = Field(default=None, description="The date on which the loan was initially lent. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).")
    origination_principal_amount: Optional[float] = Field(default=None, description="The original principal balance of the mortgage.")
    past_due_amount: Optional[float] = Field(default=None, description="Amount of loan (principal + interest) past due for payment.")
    property_address: MortgagePropertyAddress = Field()
    ytd_interest_paid: Optional[float] = Field(default=None, description="The year to date (YTD) interest paid.")
    ytd_principal_paid: Optional[float] = Field(default=None, description="The YTD principal paid.")

MortgageLiability.update_forward_refs()
