# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class MortgageInterestRate(BaseModel):
    """Object containing metadata about the interest rate for the mortgage."""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#mortgage_interest_rate"
            }
        }

    percentage: Optional[float] = Field(default=None, description="Percentage value (interest rate of current mortgage, not APR) of interest payable on a loan.")
    type: Optional[str] = Field(default=None, description="The type of interest charged (fixed or variable).")

MortgageInterestRate.update_forward_refs()
