# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.amount_with_currency import AmountWithCurrency




class NegativeBalanceOccurrence(BaseModel):
    """Details about a specific occurrence of a negative balance period, including start and end dates."""

    model_config = ConfigDict(json_schema_extra={"nullable": True})

    start_date: Optional[date_] = Field(default=None, description="The date of the first transaction that caused the account to have a negative balance. The date will be returned in an ISO 8601 format (YYYY-MM-DD).")
    end_date: Optional[date_] = Field(default=None, description="The date of the last transaction that caused the account to have a negative balance. The date will be returned in an ISO 8601 format (YYYY-MM-DD). This date is inclusive, meaning that this was the last date that the account had a negative balance.")
    minimum_balance: Optional[AmountWithCurrency] = Field(default=None,)

NegativeBalanceOccurrence.update_forward_refs()
