# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class NetworkStatusGetUser(BaseModel):
    """An object specifying information about the end user for the network status check."""


    phone_number: str = Field( description="The user's phone number in [E.164](https://en.wikipedia.org/wiki/E.164) format.")

NetworkStatusGetUser.update_forward_refs()
