# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class NumbersRetirement401k(BaseModel):
    """Identifying information for transferring holdings from a 401k account to another 401k account or IRA via the manual 401k rollover process."""


    account_id: str = Field( description="The Plaid account ID associated with the account numbers")
    plan: Optional[str] = Field(default=None, description="The plan number for the employer's 401k retirement plan")
    account: Optional[str] = Field(default=None, description="The full account number for the account")

NumbersRetirement401k.update_forward_refs()
