# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class NumbersACATS(BaseModel):
    """Identifying information for transferring holdings to an investments account via ACATS."""


    account_id: str = Field( description="The Plaid account ID associated with the account numbers")
    account: str = Field( description="The full account number for the account")
    dtc_numbers: List[str] = Field( description="Identifiers for the clearinghouses that are assocciated with the account in order of relevance. This array will be empty if we can't provide any account level data. Institution level data can be retrieved from the institutions/get endpoints.")

NumbersACATS.update_forward_refs()
