# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import ConfigDict, AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class NumbersIBANNullable(BaseModel):
    """International Bank Account Number (IBAN)."""
    model_config = ConfigDict(json_schema_extra={"nullable": True})


NumbersIBANNullable.update_forward_refs()
