# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class NumbersEFT(BaseModel):
    """Identifying information for transferring money to or from a Canadian bank account via EFT."""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#numbers_eft"
            }
        }

    account_id: str = Field( description="The Plaid account ID associated with the account numbers")
    account: str = Field( description="The EFT account number for the account")
    institution: str = Field( description="The EFT institution number for the account")
    branch: str = Field( description="The EFT branch number for the account")

NumbersEFT.update_forward_refs()
