# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class NumbersEFTNullable(BaseModel):
    """Identifying information for transferring money to or from a Canadian bank account via EFT."""


    account_id: str = Field( description="The Plaid account ID associated with the account numbers")
    account: str = Field( description="The EFT account number for the account")
    institution: str = Field( description="The EFT institution number for the account")
    branch: str = Field( description="The EFT branch number for the account")

NumbersEFTNullable.update_forward_refs()
