# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class OAuthTokenResponse(BaseModel):
    """OAuth token grant success response"""


    access_token: str = Field( description="Access token for OAuth")
    refresh_token: str = Field( description="Refresh token for OAuth")
    token_type: str = Field( description="Type of token the access token is. Currently it is always Bearer")
    expires_in: int = Field( description="Time remaining in seconds before expiration")
    request_id: str = Field( description="A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.")

OAuthTokenResponse.update_forward_refs()
