# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.payment_initiation_address import PaymentInitiationAddress




class OriginatingFundSource(BaseModel):
    """The original source of the funds. This field is required by local regulation for certain businesses (e.g. money remittance) to send payouts to recipients in the EU and UK."""

    model_config = ConfigDict(json_schema_extra={"nullable": True})

    full_name: str = Field( description="The full name associated with the source of the funds.")
    address: Optional[PaymentInitiationAddress] = Field(default=None,)
    account_number: str = Field( description="The account number from which the funds are sourced.")
    bic: str = Field( description="The Business Identifier Code, also known as SWIFT code, for this bank account.")

    @field_validator("bic")
    @classmethod
    def bic_min_length(cls, value):
        assert len(value) >= 8
        return value

    @field_validator("bic")
    @classmethod
    def bic_max_length(cls, value):
        assert len(value) <= 11
        return value

OriginatingFundSource.update_forward_refs()
