# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class PartnerEndCustomerCustomerSupportInfo(BaseModel):
    """This information is public. Users of your app will see this information when managing connections between your app and their bank accounts in Plaid Portal. Defaults to partner's customer support info if omitted."""


    email: Optional[str] = Field(default=None,)
    phone_number: Optional[str] = Field(default=None,)
    contact_url: Optional[str] = Field(default=None,)
    link_update_url: Optional[str] = Field(default=None,)

PartnerEndCustomerCustomerSupportInfo.update_forward_refs()
