# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from strenum import StrEnum

PartnerEndCustomerOAuthInstitutionApplicationStatus = StrEnum("PartnerEndCustomerOAuthInstitutionApplicationStatus", names=['NOT_STARTED', 'PROCESSING', 'APPROVED', 'ENABLED', 'ATTENTION_REQUIRED'])