# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class PartnerEndCustomerBillingContact(BaseModel):
    """The billing contact for the end customer. Defaults to partner's billing contact if omitted."""


    given_name: Optional[str] = Field(default=None,)
    family_name: Optional[str] = Field(default=None,)
    email: Optional[str] = Field(default=None,)

PartnerEndCustomerBillingContact.update_forward_refs()
