# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum


class PartnerEndCustomerQuestionnaireStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    RECEIVED = "RECEIVED"
    COMPLETE = "COMPLETE"
