# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum



class PartnerEndCustomerStatus(str, Enum):
    UNDER_REVIEW = "UNDER_REVIEW"
    PENDING_ENABLEMENT = "PENDING_ENABLEMENT"
    ACTIVE = "ACTIVE"
    DENIED = "DENIED"
    MORE_INFORMATION_NEEDED = "MORE_INFORMATION_NEEDED"
