# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class PaymentMeta(BaseModel):
    """Transaction information specific to inter-bank transfers. If the transaction was not an inter-bank transfer, all fields will be `null`.  If the `transactions` object was returned by a Transactions endpoint such as `/transactions/get`, the `payment_meta` key will always appear, but no data elements are guaranteed. If the `transactions` object was returned by an Assets endpoint such as `/asset_report/get/` or `/asset_report/pdf/get`, this field will only appear in an Asset Report with Insights."""


    reference_number: Optional[str] = Field(default=None, description="The transaction reference number supplied by the financial institution.")
    ppd_id: Optional[str] = Field(default=None, description="The ACH PPD ID for the payer.")
    payee: Optional[str] = Field(default=None, description="For transfers, the party that is receiving the transaction.")
    by_order_of: Optional[str] = Field(default=None, description="The party initiating a wire transfer. Will be `null` if the transaction is not a wire transfer.")
    payer: Optional[str] = Field(default=None, description="For transfers, the party that is paying the transaction.")
    payment_method: Optional[str] = Field(default=None, description="The type of transfer, e.g. 'ACH'")
    payment_processor: Optional[str] = Field(default=None, description="The name of the payment processor")
    reason: Optional[str] = Field(default=None, description="The payer-supplied description of the transfer.")

PaymentMeta.update_forward_refs()
