# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import ConfigDict, AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class PaymentConsentValidDateTime(BaseModel):
    """Life span for the payment consent. After the `to` date the payment consent expires and can no longer be used for payment initiation."""
    model_config = ConfigDict(json_schema_extra={"nullable": True})

    _from: Optional[datetime_] = Field(default=None, description="The date and time from which the consent should be active, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format.")
    to: Optional[datetime_] = Field(default=None, description="The date and time at which the consent expires, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format.")

PaymentConsentValidDateTime.update_forward_refs()
