# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.payment_initiation_address import PaymentInitiationAddress
from plaid_skel.models.recipient_bacs_nullable import RecipientBACSNullable




class PaymentInitiationRecipient(BaseModel):
    """PaymentInitiationRecipient defines a payment initiation recipient"""


    recipient_id: str = Field( description="The ID of the recipient.")
    name: str = Field( description="The name of the recipient.")
    address: Optional[PaymentInitiationAddress] = Field(default=None,)
    iban: Optional[str] = Field(default=None, description="The International Bank Account Number (IBAN) for the recipient.")
    bacs: Optional[RecipientBACSNullable] = Field(default=None,)

PaymentInitiationRecipient.update_forward_refs()
