# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.payment_initiation_consent_constraints import PaymentInitiationConsentConstraints
from plaid_skel.models.payment_initiation_consent_scope import PaymentInitiationConsentScope
from plaid_skel.models.payment_initiation_consent_status import PaymentInitiationConsentStatus




class PaymentInitiationConsentGetResponse(BaseModel):
    """PaymentInitiationConsentGetResponse defines the response schema for `/payment_initation/consent/get`"""


    consent_id: str = Field( description="The consent ID.")
    status: PaymentInitiationConsentStatus = Field()
    created_at: datetime_ = Field( description="Consent creation timestamp, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format.")
    recipient_id: str = Field( description="The ID of the recipient the payment consent is for.")
    reference: str = Field( description="A reference for the payment consent.")
    constraints: PaymentInitiationConsentConstraints = Field()
    scopes: List[PaymentInitiationConsentScope] = Field( description="An array of payment consent scopes.")
    request_id: str = Field( description="A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.")

    @field_validator("consent_id")
    @classmethod
    def consent_id_min_length(cls, value):
        assert len(value) >= 1
        return value

    @field_validator("recipient_id")
    @classmethod
    def recipient_id_min_length(cls, value):
        assert len(value) >= 1
        return value

PaymentInitiationConsentGetResponse.update_forward_refs()
