# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from strenum import StrEnum

PaystubPayFrequency = StrEnum("PaystubPayFrequency", names=['MONTHLY', 'BI-WEEKLY', 'WEEKLY', 'SEMI-MONTHLY'])