# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.paystub_override_employee_address import PaystubOverrideEmployeeAddress




class PaystubOverrideEmployee(BaseModel):
    """The employee on the paystub."""


    name: Optional[str] = Field(default=None, description="The name of the employee.")
    address: Optional[PaystubOverrideEmployeeAddress] = Field(default=None,)

PaystubOverrideEmployee.update_forward_refs()
