# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class PaystubOverrideEmployeeAddress(BaseModel):
    """The address of the employee."""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#paystub_override_employee_address"
            }
        }

    city: Optional[str] = Field(default=None, description="The full city name.")
    region: Optional[str] = Field(default=None, description="The region or state Example: `\"NC\"`")
    street: Optional[str] = Field(default=None, description="The full street address Example: `\"564 Main Street, APT 15\"`")
    postal_code: Optional[str] = Field(default=None, description="5 digit postal code.")
    country: Optional[str] = Field(default=None, description="The country of the address.")

PaystubOverrideEmployeeAddress.update_forward_refs()
