# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.webhook_environment_values import WebhookEnvironmentValues




class PendingExpirationWebhook(BaseModel):
    """Fired when an Item’s access consent is expiring in 7 days. This can be resolved by having the user go through Link’s update mode. This webhook is fired only for Items associated with institutions in Europe (including the UK); for Items associated with institutions in the US or Canada, see [`PENDING_DISCONNECT`](https://plaid.com/docs/api/items/#pending_disconnect) instead."""


    webhook_type: str = Field( description="`ITEM`")
    webhook_code: str = Field( description="`PENDING_EXPIRATION`")
    item_id: str = Field( description="The `item_id` of the Item associated with this webhook, warning, or error")
    consent_expiration_time: datetime_ = Field( description="The date and time at which the Item's access consent will expire, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format.")
    environment: WebhookEnvironmentValues = Field()

PendingExpirationWebhook.update_forward_refs()
