# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class PrismCashScoreMetadata(BaseModel):
    """An object containing metadata about the provided transactions."""


    max_age: Optional[int] = Field(default=None, description="Number of days since the oldest transaction.")
    min_age: Optional[int] = Field(default=None, description="Number of days since the latest transaction.")
    min_age_credit: Optional[int] = Field(default=None, description="Number of days since the latest credit transaction.")
    min_age_debit: Optional[int] = Field(default=None, description="Number of days since the latest debit transaction.")
    max_age_debit: Optional[int] = Field(default=None, description="Number of days since the oldest debit transaction.")
    max_age_credit: Optional[int] = Field(default=None, description="Number of days since the oldest credit transaction.")
    num_trxn_credit: Optional[int] = Field(default=None, description="Number of credit transactions.")
    num_trxn_debit: Optional[int] = Field(default=None, description="Number of debit transactions.")
    l1m_credit_value_cnt: Optional[int] = Field(default=None, description="Number of credit transactions in the last 30 days.")
    l1m_debit_value_cnt: Optional[int] = Field(default=None, description="Number of debit transactions in the last 30 days.")

PrismCashScoreMetadata.update_forward_refs()
