# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.account_base import AccountBase
from plaid_skel.models.holding import Holding
from plaid_skel.models.security import Security




class ProcessorInvestmentsHoldingsGetResponse(BaseModel):
    """ProcessorInvestmentsHoldingsGetResponse defines the response schema for `/processor/invesments/holdings/get`"""


    account: AccountBase = Field()
    holdings: List[Holding] = Field( description="The holdings belonging to investment accounts associated with the Item. Details of the securities in the holdings are provided in the `securities` field. ")
    securities: List[Security] = Field( description="Objects describing the securities held in the account.")
    is_investments_fallback_item: Optional[bool] = Field(default=None, description="When true, this field indicates that the Item's portfolio was manually created with the Investments Fallback flow.")
    request_id: Optional[str] = Field(default=None, description="A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.")

ProcessorInvestmentsHoldingsGetResponse.update_forward_refs()
