# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class ProcessorStripeBankAccountTokenCreateResponse(BaseModel):
    """ProcessorStripeBankAccountTokenCreateResponse defines the response schema for `/processor/stripe/bank_account/create`"""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#processor_stripe_bank_account_token_create_response"
            }
        }

    stripe_bank_account_token: str = Field( description="A token that can be sent to Stripe for use in making API calls to Plaid")
    request_id: str = Field( description="A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.")

ProcessorStripeBankAccountTokenCreateResponse.update_forward_refs()
