# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.plaid_error import PlaidError
from plaid_skel.models.webhook_environment_values import WebhookEnvironmentValues




class ProcessorTokenWebhookUpdate(BaseModel):
    """This webhook is only sent to [Plaid processor partners](https://plaid.com/docs/auth/partnerships/).  Fired when a processor updates the webhook URL for a processor token via `/processor/token/webhook/update`."""


    webhook_type: str = Field( description="`PROCESSOR_TOKEN`")
    webhook_code: str = Field( description="`WEBHOOK_UPDATE_ACKNOWLEDGED`")
    error: Optional[PlaidError] = Field(default=None,)
    account_id: str = Field( description="The ID of the account.")
    new_webhook_url: str = Field( description="The new webhook URL.")
    environment: WebhookEnvironmentValues = Field()

ProcessorTokenWebhookUpdate.update_forward_refs()
