# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum


class Products(str, Enum):
    BALANCE = "balance"
    AUTH = "auth"
    IDENTITY = "identity"
    TRANSACTIONS = "transactions"
