# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum


class Products(str, Enum):
    ASSETS = "assets"
    AUTH = "auth"
    BALANCE = "balance"
    IDENTITY = "identity"
    INVESTMENTS = "investments"
    LIABILITIES = "liabilities"
    PAYMENT_INITIATION = "payment_initiation"
    IDENTITY_VERIFICATION = "identity_verification"
    TRANSACTIONS = "transactions"
    CREDIT_DETAILS = "credit_details"
    INCOME = "income"
    INCOME_VERIFICATION = "income_verification"
    DEPOSIT_SWITCH = "deposit_switch"
    STANDING_ORDERS = "standing_orders"
    TRANSFER = "transfer"
    EMPLOYMENT = "employment"
    RECURRING_TRANSACTIONS = "recurring_transactions"
    SIGNAL = "signal"
