# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum


class Products(str, Enum):
    ASSETS = "assets"
    IDENTITY = "identity"
    TRANSACTIONS = "transactions"
    AUTH = "auth"
    BALANCE = "balance"
