# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from strenum import StrEnum

ProgramNameSensitivity = StrEnum("ProgramNameSensitivity", names=['coarse', 'balanced', 'strict', 'exact'])