# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class ProtectEvent(BaseModel):
    """Event data for Protect events."""

    model_config = ConfigDict(json_schema_extra={"nullable": True})

    timestamp: datetime_ = Field( description="The timestamp of the event, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format, e.g. `\"2017-09-14T14:42:19.350Z\"`")
    protect_session_id: Optional[str] = Field(default=None, description="If present, contains the current Protect Session ID from the Plaid Pixel SDK.")
    app_visit: Optional[Dict[str, Any]] = Field(default=None, description="This event type represents a user visiting the client application.")
    user_sign_in: Optional[Dict[str, Any]] = Field(default=None, description="This event type represents a user signing in to the application.")
    user_sign_up: Optional[Dict[str, Any]] = Field(default=None, description="This event type represents a user signing up for the application.")

ProtectEvent.update_forward_refs()
