# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.protect_event import ProtectEvent




class ProtectEventSendRequest(BaseModel):
    """Request object for /protect/event/send"""


    client_id: Optional[str] = Field(default=None, description="Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.")
    secret: Optional[str] = Field(default=None, description="Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.")
    timestamp: Optional[datetime_] = Field(default=None, description="Timestamp of the event. Might be the current moment or a time in the past. In [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format, e.g. `\"2017-09-14T14:42:19.350Z\"`")
    event: Optional[ProtectEvent] = Field(default=None,)
    protect_session_id: Optional[str] = Field(default=None, description="Protect Session ID should be provided for any event correlated with a frontend user session started via the Protect SDK.")
    request_trust_index: Optional[bool] = Field(default=None, description="Whether this event should be scored with Trust Index. The default is false.")

ProtectEventSendRequest.update_forward_refs()
