# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import ConfigDict, AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.risk_check_linked_service import RiskCheckLinkedService




class RiskCheckPhone(BaseModel):
    """Result summary object specifying values for `phone` attributes of risk check."""
    model_config = ConfigDict(json_schema_extra={"nullable": True})

    linked_services: list[RiskCheckLinkedService] = Field()

RiskCheckPhone.update_forward_refs()
