# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.risk_check_behavior_bot_detected_label import RiskCheckBehaviorBotDetectedLabel
from plaid_skel.models.risk_check_behavior_fraud_ring_detected_label import RiskCheckBehaviorFraudRingDetectedLabel
from plaid_skel.models.risk_check_behavior_user_interactions_label import RiskCheckBehaviorUserInteractionsLabel




class RiskCheckBehavior(BaseModel):
    """Result summary object specifying values for `behavior` attributes of risk check, when available."""


    user_interactions: RiskCheckBehaviorUserInteractionsLabel = Field()
    fraud_ring_detected: RiskCheckBehaviorFraudRingDetectedLabel = Field()
    bot_detected: RiskCheckBehaviorBotDetectedLabel = Field()

RiskCheckBehavior.update_forward_refs()
