# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum


from pydantic import GetJsonSchemaHandler
from pydantic.json_schema import JsonSchemaValue



class RiskSignalFileType(str, Enum):
    UNKNOWN = "UNKNOWN"
    IMAGE_PDF = "IMAGE_PDF"
    SCAN_OCR = "SCAN_OCR"
    TRUE_PDF = "TRUE_PDF"
    IMAGE = "IMAGE"
    MIXED_PAGE_PDF = "MIXED_PAGE_PDF"
    EMPTY_PDF = "EMPTY_PDF"
    FLATTENED_PDF = "FLATTENED_PDF"

# Nullable OpenAPI enum
@classmethod
def __get_pydantic_json_schema__(cls, field_schema: dict, handler: GetJsonSchemaHandler) -> JsonSchemaValue:
    schema = handler(field_schema)
    schema["nullable"] = True
    return schema
