# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.proxy_type import ProxyType




class RiskCheckDevice(BaseModel):
    """Result summary object specifying values for `device` attributes of risk check."""


    ip_proxy_type: Optional[ProxyType] = Field(default=None,)
    ip_spam_list_count: Optional[int] = Field(default=None, description="Count of spam lists the IP address is associated with if known.")
    ip_timezone_offset: Optional[str] = Field(default=None, description="UTC offset of the timezone associated with the IP address.")

RiskCheckDevice.update_forward_refs()
