# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum

from pydantic import GetJsonSchemaHandler
from pydantic.json_schema import JsonSchemaValue


class RiskCheckEmailDomainIsDisposable(str, Enum):
    YES = "yes"
    NO = "no"
    NO_DATA = "no_data"
