# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum



class RiskCheckEmailTopLevelDomainIsSuspicious(str, Enum):
    YES = "yes"
    NO = "no"
    NO_DATA = "no_data"
