# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.party_role_type import PartyRoleType




class RoleDetail(BaseModel):
    """Documentation not found in the MISMO model viewer and not provided by Freddie Mac."""


    party_role_type: PartyRoleType = Field()

RoleDetail.update_forward_refs()
