# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class RuleDetails(BaseModel):
    """Rules are run in numerical order. The first rule with a logic match is triggered. These are the details of that rule."""

    model_config = ConfigDict(json_schema_extra={"nullable": True})

    internal_note: Optional[str] = Field(default=None, description="An optional message attached to the triggered rule, defined within the Dashboard, for your internal use. Useful for debugging, such as “Account appears to be closed.”")
    custom_action_key: Optional[str] = Field(default=None, description="A string key, defined within the Dashboard, used to trigger programmatic behavior for a certain result. For instance, you could optionally choose to define a \"3-day-hold\" `custom_action_key` for an ACCEPT result.")

RuleDetails.update_forward_refs()
