# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class SandboxItemFireWebhookResponse(BaseModel):
    """SandboxItemFireWebhookResponse defines the response schema for `/sandbox/item/fire_webhook`"""


    webhook_fired: bool = Field( description="Value is `true`  if the test` webhook_code`  was successfully fired.")
    request_id: str = Field( description="A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.")

SandboxItemFireWebhookResponse.update_forward_refs()
