# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class SandboxPaymentProfileResetLoginResponse(BaseModel):
    """SandboxPaymentProfileResetLoginResponse defines the response schema for `/sandbox/payment_profile/reset_login`"""


    reset_login: bool = Field( description="`true` if the call succeeded")
    request_id: str = Field( description="A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.")

SandboxPaymentProfileResetLoginResponse.update_forward_refs()
