# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum



class SandboxBankIncomeWebhookFireRequestWebhookCode(str, Enum):
    BANK_INCOME_REFRESH_UPDATE = "BANK_INCOME_REFRESH_UPDATE"
    BANK_INCOME_REFRESH_COMPLETE = "BANK_INCOME_REFRESH_COMPLETE"
