# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class SandboxProcessorTokenCreateRequestOptions(BaseModel):
    """An optional set of options to be used when configuring the Item. If specified, must not be `null`."""


    override_username: Optional[str] = Field(default=None, description="Test username to use for the creation of the Sandbox Item. Default value is `user_good`.")
    override_password: Optional[str] = Field(default=None, description="Test password to use for the creation of the Sandbox Item. Default value is `pass_good`.")

SandboxProcessorTokenCreateRequestOptions.update_forward_refs()
