# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.simulated_transfer_sweep import SimulatedTransferSweep




class SandboxTransferSweepSimulateResponse(BaseModel):
    """Defines the response schema for `/sandbox/transfer/sweep/simulate`"""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#sandbox_transfer_sweep_simulate_response"
            }
        }

    sweep: Optional[SimulatedTransferSweep] = Field(default=None,)
    request_id: str = Field( description="A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.")

SandboxTransferSweepSimulateResponse.update_forward_refs()
