# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class SelfieCapture(BaseModel):
    """The image or video capture of a selfie. Only one of image or video URL will be populated per selfie."""


    image_url: Optional[str] = Field(default=None, description="Temporary URL for downloading an image selfie capture.")
    video_url: Optional[str] = Field(default=None, description="Temporary URL for downloading a video selfie capture.")

SelfieCapture.update_forward_refs()
