# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class SignalPersonName(BaseModel):
    """The user's legal name"""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#signal_person_name"
            }
            , "nullable": True,
        }

    prefix: Optional[str] = Field(default=None, description="The user's name prefix (e.g. \"Mr.\")")
    given_name: Optional[str] = Field(default=None, description="The user's given name. If the user has a one-word name, it should be provided in this field.")
    middle_name: Optional[str] = Field(default=None, description="The user's middle name")
    family_name: Optional[str] = Field(default=None, description="The user's family name / surname")
    suffix: Optional[str] = Field(default=None, description="The user's name suffix (e.g. \"II\")")

SignalPersonName.update_forward_refs()
