# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum



class SignalScheduleDefaultPaymentMethod(str, Enum):
    SAME_DAY_ACH = "SAME_DAY_ACH"
    STANDARD_ACH = "STANDARD_ACH"
    MULTIPLE_PAYMENT_METHODS = "MULTIPLE_PAYMENT_METHODS"
