# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.signal_evaluate_core_attributes import SignalEvaluateCoreAttributes
from plaid_skel.models.signal_scores import SignalScores
from plaid_skel.models.signal_warning import SignalWarning




class SignalEvaluateResponse(BaseModel):
    """SignalEvaluateResponse defines the response schema for `/signal/income/evaluate`"""


    request_id: str = Field( description="A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.")
    scores: SignalScores = Field()
    core_attributes: Optional[SignalEvaluateCoreAttributes] = Field(default=None,)
    warnings: Optional[List[SignalWarning]] = Field(default=None, description="If bank information was not able to be used as features into the Signal model, this array contains warnings describing why we were missing bank data")

SignalEvaluateResponse.update_forward_refs()
