# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class SignalWarning(BaseModel):
    """Conveys information about the errors causing missing or stale bank data used to construct the /signal/evaluate scores and response"""


    warning_type: Optional[str] = Field(default=None, description="A broad categorization of the warning. Safe for programmatic use.")
    warning_code: Optional[str] = Field(default=None, description="The warning code identifies a specific kind of warning that pertains to the error causing bank data to be missing. Safe for programmatic use. For more details on warning codes, please refer to Plaid standard error codes documentation. If you receive the `ITEM_LOGIN_REQUIRED` warning, we recommend re-authenticating your user by implementing Link's update mode. This will guide your user to fix their credentials, allowing Plaid to start fetching data again for future requests.")
    warning_message: Optional[str] = Field(default=None, description="A developer-friendly representation of the warning type. This may change over time and is not safe for programmatic use.")

SignalWarning.update_forward_refs()
