# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.signal_schedule_default_payment_method import SignalScheduleDefaultPaymentMethod




class SignalScheduleRequest(BaseModel):
    """SignalScheduleRequest defines the request schema for `/signal/schedule`"""


    client_id: Optional[str] = Field(default=None, description="Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.")
    secret: Optional[str] = Field(default=None, description="Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.")
    access_token: str = Field( description="The access token associated with the Item data is being requested for.")
    account_id: str = Field( description="The Plaid `account_id` of the account that is the funding source for the proposed transaction. The `account_id` is returned in the `/accounts/get` endpoint as well as the [`onSuccess`](https://plaid.com/docs/link/ios/#link-ios-onsuccess-linkSuccess-metadata-accounts-id) callback metadata.  This will return an [`INVALID_ACCOUNT_ID`](https://plaid.com/docs/errors/invalid-input/#invalid_account_id) error if the account has been removed at the bank or if the `account_id` is no longer valid.")
    client_transaction_id: str = Field( description="The unique ID that you would like to use to refer to this transaction. For your convenience mapping your internal data, you could use your internal ID/identifier for this transaction. The max length for this field is 36 characters.")
    amount: float = Field( description="The transaction amount, in USD (e.g. `102.05`)")
    default_payment_method: Optional[SignalScheduleDefaultPaymentMethod] = Field(default=None,)

    @field_validator("client_transaction_id")
    @classmethod
    def client_transaction_id_min_length(cls, value):
        assert len(value) >= 1
        return value

    @field_validator("client_transaction_id")
    @classmethod
    def client_transaction_id_max_length(cls, value):
        assert len(value) <= 36
        return value

SignalScheduleRequest.update_forward_refs()
