# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class StandaloneInvestmentTransactionType(BaseModel):
    """Valid values for investment transaction types and subtypes. Note that transactions representing inflow of cash will appear as negative amounts, outflow of cash will appear as positive amounts."""


    buy: str = Field( description="Buying an investment")
    sell: str = Field( description="Selling an investment")
    cancel: str = Field( description="A cancellation of a pending transaction")
    cash: str = Field( description="Activity that modifies a cash position")
    fee: str = Field( description="Fees on the account, e.g. commission, bookkeeping, options-related.")
    transfer: str = Field( description="Activity that modifies a position, but not through buy/sell activity e.g. options exercise, portfolio transfer")

StandaloneInvestmentTransactionType.update_forward_refs()
