# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class StandaloneCurrencyCodeList(BaseModel):
    """The following currency codes are supported by Plaid."""


    iso_currency_code: str = Field( description="Plaid supports all ISO 4217 currency codes.")
    unofficial_currency_code: str = Field( description="List of unofficial currency codes")

StandaloneCurrencyCodeList.update_forward_refs()
