# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.statements_refresh_complete_result import StatementsRefreshCompleteResult
from plaid_skel.models.webhook_environment_values import WebhookEnvironmentValues




class StatementsRefreshCompleteWebhook(BaseModel):
    """Fired when refreshed statements extraction is completed or failed to be completed. Triggered by calling `/statements/refresh`."""


    webhook_type: str = Field( description="`STATEMENTS`")
    webhook_code: str = Field( description="`STATEMENTS_REFRESH_COMPLETE`")
    item_id: str = Field( description="The Plaid Item ID. The `item_id` is always unique; linking the same account at the same institution twice will result in two Items with different `item_id` values. Like all Plaid identifiers, the `item_id` is case-sensitive.")
    result: StatementsRefreshCompleteResult = Field()
    environment: WebhookEnvironmentValues = Field()

StatementsRefreshCompleteWebhook.update_forward_refs()
