# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class SweepFailure(BaseModel):
    """The failure reason if the status for a sweep is `\"failed\"` or `\"returned\"`. Null value otherwise."""

    model_config = ConfigDict(json_schema_extra={"nullable": True})

    failure_code: Optional[str] = Field(default=None, description="The failure code, e.g. `R01`.  A failure code will be provided if and only if the sweep status is `returned`. See [ACH return codes](https://plaid.com/docs/errors/transfer/#ach-return-codes) for a full listing of ACH return codes and [RTP/RfP error codes](https://plaid.com/docs/errors/transfer/#rtprfp-error-codes) for RTP error codes.")
    description: Optional[str] = Field(default=None, description="A human-readable description of the reason for the failure or reversal.")

SweepFailure.update_forward_refs()
