# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.w2 import W2




class Taxform(BaseModel):
    """Data about an official document used to report the user's income to the IRS."""


    doc_id: Optional[str] = Field(default=None, description="An identifier of the document referenced by the document metadata.")
    document_type: str = Field( description="The type of tax document. Currently, the only supported value is `w2`.")
    w2: Optional[W2] = Field(default=None,)

Taxform.update_forward_refs()
