# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from strenum import StrEnum

TaxpayerIdentifierType = StrEnum("TaxpayerIdentifierType", names=['IndividualTaxpayerIdentificationNumber', 'SocialSecurityNumber'])