# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class TotalMonthlyIncomeInsights(BaseModel):
    """Details about about the total monthly income"""


    baseline_amount: Optional[float] = Field(default=None, description="The aggregated income for the 30 days prior to subscription date")
    current_amount: float = Field( description="The aggregated income of the last 30 days")

TotalMonthlyIncomeInsights.update_forward_refs()
