# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from strenum import StrEnum

TransactionStreamStatus = StrEnum("TransactionStreamStatus", names=['UNKNOWN', 'MATURE', 'EARLY_DETECTION', 'TOMBSTONED'])