# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.ach_class import ACHClass
from plaid_skel.models.transfer_authorization_guarantee_decision import TransferAuthorizationGuaranteeDecision
from plaid_skel.models.transfer_authorization_guarantee_decision_rationale import TransferAuthorizationGuaranteeDecisionRationale
from plaid_skel.models.transfer_failure import TransferFailure
from plaid_skel.models.transfer_network import TransferNetwork
from plaid_skel.models.transfer_refund import TransferRefund
from plaid_skel.models.transfer_status import TransferStatus
from plaid_skel.models.transfer_sweep_status import TransferSweepStatus
from plaid_skel.models.transfer_type import TransferType
from plaid_skel.models.transfer_user_in_response import TransferUserInResponse




class Transfer(BaseModel):
    """Represents a transfer within the Transfers API."""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#transfer"
            }
        }

    id: str = Field( description="Plaid’s unique identifier for a transfer.")
    ach_class: Optional[ACHClass] = Field(default=None,)
    account_id: Optional[str] = Field(default=None, description="The Plaid `account_id` corresponding to the end-user account that will be debited or credited.")
    funding_account_id: str = Field( description="The id of the funding account to use, available in the Plaid Dashboard. This determines which of your business checking accounts will be credited or debited.")
    type: TransferType = Field()
    user: TransferUserInResponse = Field()
    amount: str = Field( description="The amount of the transfer (decimal string with two digits of precision e.g. \"10.00\").")
    description: str = Field( description="The description of the transfer.")
    created: datetime = Field( description="The datetime when this transfer was created. This will be of the form `2006-01-02T15:04:05Z`")
    status: TransferStatus = Field()
    sweep_status: Optional[TransferSweepStatus] = Field(default=None,)
    network: TransferNetwork = Field()
    cancellable: bool = Field( description="When `true`, you can still cancel this transfer.")
    failure_reason: Optional[TransferFailure] = Field(default=None,)
    metadata: Optional[Dict[str, str]] = Field(default=None, description="The Metadata object is a mapping of client-provided string fields to any string value. The following limitations apply: The JSON values must be Strings (no nested JSON objects allowed) Only ASCII characters may be used Maximum of 50 key/value pairs Maximum key length of 40 characters Maximum value length of 500 characters ")
    origination_account_id: str = Field( description="Plaid’s unique identifier for the origination account that was used for this transfer.")
    guarantee_decision: Optional[TransferAuthorizationGuaranteeDecision] = Field(default=None,)
    guarantee_decision_rationale: Optional[TransferAuthorizationGuaranteeDecisionRationale] = Field(default=None,)
    iso_currency_code: str = Field( description="The currency of the transfer amount, e.g. \"USD\"")
    standard_return_window: Optional[date] = Field(default=None, description="The date 3 business days from settlement date indicating the following ACH returns can no longer happen: R01, R02, R03, R29. This will be of the form YYYY-MM-DD.")
    unauthorized_return_window: Optional[date] = Field(default=None, description="The date 61 business days from settlement date indicating the following ACH returns can no longer happen: R05, R07, R10, R11, R51, R33, R37, R38, R51, R52, R53. This will be of the form YYYY-MM-DD.")
    expected_settlement_date: Optional[date] = Field(default=None, description="An estimation of the settlement date which can be useful when the transfer is `pending`. Only set for ACH transfers and is `null` for non-ACH transfers. This will be of the form YYYY-MM-DD.")
    originator_client_id: Optional[str] = Field(default=None, description="The Plaid client ID that is the originator of this transfer. Only present if created on behalf of another client as a third-party sender (TPS).")
    refunds: List[TransferRefund] = Field( description="A list of refunds associated with this transfer.")
    recurring_transfer_id: Optional[str] = Field(default=None, description="The id of the recurring transfer if this transfer belongs to a recurring transfer.")

Transfer.update_forward_refs()
