# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class TransferCapabilitiesGetRfP(BaseModel):
    """Contains the supported service types in RfP"""


    debit: Optional[bool] = Field(default=None, description="When `true`, the linked Item's institution supports RfP debit transfer.")
    max_amount: Optional[str] = Field(default=None, description="The maximum amount (decimal string with two digits of precision e.g. \"10.00\") for originating RfP transfers with the given institution.")
    iso_currency_code: Optional[str] = Field(default=None, description="The currency of the `max_amount`, e.g. \"USD\".")

TransferCapabilitiesGetRfP.update_forward_refs()
