# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum


class TransferEventType(str, Enum):
    PENDING = "pending"
    CANCELLED = "cancelled"
    FAILED = "failed"
    POSTED = "posted"
    SETTLED = "settled"
    RETURNED = "returned"
    SWEPT = "swept"
    SWEPT_SETTLED = "swept_settled"
    RETURN_SWEPT = "return_swept"
    SWEEP_PENDING = "sweep.pending"
    SWEEP_POSTED = "sweep.posted"
    SWEEP_SETTLED = "sweep.settled"
    SWEEP_RETURNED = "sweep.returned"
    SWEEP_FAILED = "sweep.failed"
