# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum

from pydantic import GetJsonSchemaHandler
from pydantic.json_schema import JsonSchemaValue


class TransactionStreamStatus(str, Enum):
    UNKNOWN = "UNKNOWN"
    MATURE = "MATURE"
    EARLY_DETECTION = "EARLY_DETECTION"
    TOMBSTONED = "TOMBSTONED"
