# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from strenum import StrEnum

TransferRecurringStatus = StrEnum("TransferRecurringStatus", names=['active', 'cancelled', 'expired'])