# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import ConfigDict, AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class TransferFailure(BaseModel):
    """The failure reason if the event type for a transfer is `\"failed\"` or `\"returned\"`. Null value otherwise."""
    model_config = ConfigDict(json_schema_extra={"nullable": True})

    ach_return_code: Optional[str] = Field(default=None, description="The ACH return code, e.g. `R01`.  A return code will be provided if and only if the transfer status is `returned`. For a full listing of ACH return codes, see [Transfer errors](https://plaid.com/docs/errors/transfer/#ach-return-codes).")
    description: Optional[str] = Field(default=None, description="A human-readable description of the reason for the failure or reversal.")

TransferFailure.update_forward_refs()
