# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from strenum import StrEnum

TransferAuthorizationDecisionRationaleCode = StrEnum("TransferAuthorizationDecisionRationaleCode", names=['NSF', 'RISK', 'TRANSFER_LIMIT_REACHED', 'MANUALLY_VERIFIED_ITEM', 'ITEM_LOGIN_REQUIRED', 'PAYMENT_PROFILE_LOGIN_REQUIRED', 'ERROR', 'MIGRATED_ACCOUNT_ITEM'])