# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.transfer_refund_status import TransferRefundStatus




class TransferRefund(BaseModel):
    """Represents a refund within the Transfers API."""


    id: str = Field( description="Plaid’s unique identifier for a refund.")
    transfer_id: str = Field( description="The ID of the transfer to refund.")
    amount: str = Field( description="The amount of the refund (decimal string with two digits of precision e.g. \"10.00\").")
    status: TransferRefundStatus = Field()
    created: datetime = Field( description="The datetime when this refund was created. This will be of the form `2006-01-02T15:04:05Z`")

TransferRefund.update_forward_refs()
