# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.transfer_funding_account_with_display_name import TransferFundingAccountWithDisplayName




class TransferOriginatorFundingAccountCreateRequest(BaseModel):
    """Defines the request schema for `/transfer/originator/funding_account/create`"""


    client_id: Optional[str] = Field(default=None, description="Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.")
    secret: Optional[str] = Field(default=None, description="Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.")
    originator_client_id: str = Field( description="The Plaid client ID of the transfer originator.")
    funding_account: TransferFundingAccountWithDisplayName = Field()

TransferOriginatorFundingAccountCreateRequest.update_forward_refs()
