# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class TransferLedgerDistributeRequest(BaseModel):
    """Defines the request schema for `/transfer/ledger/distribute`"""


    client_id: Optional[str] = Field(default=None, description="Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.")
    secret: Optional[str] = Field(default=None, description="Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.")
    from_ledger_id: str = Field( description="The Ledger to pull money from.")
    to_ledger_id: str = Field( description="The Ledger to credit money to.")
    amount: str = Field( description="The amount to move (decimal string with two digits of precision e.g. \"10.00\"). Amount must be positive.")
    idempotency_key: str = Field( description="A unique key provided by the client, per unique ledger distribute. Maximum of 50 characters.  The API supports idempotency for safely retrying the request without accidentally performing the same operation twice. For example, if a request to create a ledger distribute fails due to a network connection error, you can retry the request with the same idempotency key to guarantee that only a single distribute is created.")
    description: Optional[str] = Field(default=None, description="An optional description for the ledger distribute operation.")

    @field_validator("idempotency_key")
    @classmethod
    def idempotency_key_max_length(cls, value):
        assert len(value) <= 50
        return value

TransferLedgerDistributeRequest.update_forward_refs()
