# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class TransferUserAddressInResponse(BaseModel):
    """The address associated with the account holder."""

    model_config = ConfigDict(json_schema_extra={"nullable": True})

    street: Optional[str] = Field(default=None, description="The street number and name (i.e., \"100 Market St.\").")
    city: Optional[str] = Field(default=None, description="Ex. \"San Francisco\"")
    region: Optional[str] = Field(default=None, description="The state or province (e.g., \"CA\").")
    postal_code: Optional[str] = Field(default=None, description="The postal code (e.g., \"94103\").")
    country: Optional[str] = Field(default=None, description="A two-letter country code (e.g., \"US\").")

TransferUserAddressInResponse.update_forward_refs()
