# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum



class TransferAuthorizationDecision(str, Enum):
    APPROVED = "approved"
    DECLINED = "declined"
    USER_ACTION_REQUIRED = "user_action_required"
