# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class TransactionsRecurringCreateInput(BaseModel):
    """TransactionsRecurringCreateInput defines a single input to the `/transactions/recurring/streams/create` endpoint."""


    transaction_ids: Optional[List[str]] = Field(default=None, description="IDs of all the transactions that will be merged into one stream. If any transaction currently exists in another stream, it will be removed from the other stream.")

TransactionsRecurringCreateInput.update_forward_refs()
