# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.ach_class import ACHClass
from plaid_skel.models.transfer_intent_create_mode import TransferIntentCreateMode
from plaid_skel.models.transfer_intent_create_network import TransferIntentCreateNetwork
from plaid_skel.models.transfer_user_in_request import TransferUserInRequest




class TransferIntentCreateRequest(BaseModel):
    """Defines the request schema for `/transfer/intent/create`"""


    client_id: Optional[str] = Field(default=None, description="Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.")
    secret: Optional[str] = Field(default=None, description="Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.")
    account_id: Optional[str] = Field(default=None, description="The Plaid `account_id` corresponding to the end-user account that will be debited or credited.")
    funding_account_id: Optional[str] = Field(default=None, description="Specify the account used to fund the transfer. Should be specified if using legacy funding methods only. If using Plaid Ledger, leave this field blank. Customers can find a list of `funding_account_id`s in the Accounts page of your Plaid Dashboard, under the \"Account ID\" column. If this field is left blank and you are using legacy funding methods, this will default to the default `funding_account_id` specified during onboarding. Otherwise, Plaid Ledger will be used.")
    mode: TransferIntentCreateMode = Field()
    network: Optional[TransferIntentCreateNetwork] = Field(default=None,)
    amount: str = Field( description="The amount of the transfer (decimal string with two digits of precision e.g. \"10.00\"). When calling `/transfer/authorization/create`, specify the maximum amount to authorize. When calling `/transfer/create`, specify the exact amount of the transfer, up to a maximum of the amount authorized. If this field is left blank when calling `/transfer/create`, the maximum amount authorized in the `authorization_id` will be sent.")
    description: str = Field( description="A description for the underlying transfer. Maximum of 15 characters.")
    ach_class: Optional[ACHClass] = Field(default=None,)
    origination_account_id: Optional[str] = Field(default=None, description="Plaid’s unique identifier for the origination account for the intent. If not provided, the default account will be used.")
    user: TransferUserInRequest = Field()
    metadata: Optional[Dict[str, str]] = Field(default=None, description="The Metadata object is a mapping of client-provided string fields to any string value. The following limitations apply: The JSON values must be Strings (no nested JSON objects allowed) Only ASCII characters may be used Maximum of 50 key/value pairs Maximum key length of 40 characters Maximum value length of 500 characters ")
    iso_currency_code: Optional[str] = Field(default=None, description="The currency of the transfer amount, e.g. \"USD\"")
    require_guarantee: Optional[bool] = Field(default=None, description="When `true`, the transfer requires a `GUARANTEED` decision by Plaid to proceed (Guarantee customers only).")

    @field_validator("description")
    @classmethod
    def description_min_length(cls, value):
        assert len(value) >= 1
        return value

    @field_validator("description")
    @classmethod
    def description_max_length(cls, value):
        assert len(value) <= 15
        return value

TransferIntentCreateRequest.update_forward_refs()
