# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class TransferLedgerBalance(BaseModel):
    """Information about the balance of the ledger held with Plaid."""


    available: str = Field( description="The amount of this balance available for use (decimal string with two digits of precision e.g. \"10.00\").")
    pending: str = Field( description="The amount of pending funds that are in processing (decimal string with two digits of precision e.g. \"10.00\").")

TransferLedgerBalance.update_forward_refs()
