# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.ach_class import ACHClass
from plaid_skel.models.originator_expected_transfer_frequency import OriginatorExpectedTransferFrequency




class TransferDebitUsageConfiguration(BaseModel):
    """Specifies the originator's expected usage of debits. For all dollar amounts, use a decimal string with two digits of precision e.g. \"10.00\". This field is required if the originator is expected to process debit transfers."""

    model_config = ConfigDict(json_schema_extra={"nullable": True})

    expected_frequency: OriginatorExpectedTransferFrequency = Field()
    expected_highest_amount: str = Field( description="The originator’s expected highest amount for a single debit transfer.")
    expected_average_amount: str = Field( description="The originator’s expected average amount per debit.")
    expected_monthly_amount: str = Field( description="The originator’s monthly expected ACH debit processing amount for the next 6-12 months.")
    sec_codes: List[ACHClass] = Field( description="Specifies the expected use cases for the originator’s debit transfers. This should be a list that contains one or more of the following codes:  `\"ccd\"` - Corporate Credit or Debit - fund transfer between two corporate bank accounts  `\"ppd\"` - Prearranged Payment or Deposit - the transfer is part of a pre-existing relationship with a consumer, eg. bill payment  `\"tel\"` - Telephone-Initiated Entry  `\"web\"` - Internet-Initiated Entry - debits from a consumer’s account where their authorization is obtained over the Internet")

TransferDebitUsageConfiguration.update_forward_refs()
