# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class TransferMetricsGetResponse(BaseModel):
    """Defines the response schema for `/transfer/metrics/get`"""


    request_id: str = Field( description="A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.")
    daily_debit_transfer_volume: str = Field( description="Sum of dollar amount of debit transfers in last 24 hours (decimal string with two digits of precision e.g. \"10.00\").")
    daily_credit_transfer_volume: str = Field( description="Sum of dollar amount of credit transfers in last 24 hours (decimal string with two digits of precision e.g. \"10.00\").")
    monthly_transfer_volume: str = Field( description="Sum of dollar amount of credit and debit transfers in current calendar month (decimal string with two digits of precision e.g. \"10.00\").")
    iso_currency_code: str = Field( description="The currency of the dollar amount, e.g. \"USD\".")

TransferMetricsGetResponse.update_forward_refs()
