# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.transfer_repayment_return import TransferRepaymentReturn




class TransferRepaymentReturnListResponse(BaseModel):
    """Defines the response schema for `/transfer/repayments/return/list`"""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#transfer_repayment_return_list_response"
            }
        }

    repayment_returns: List[TransferRepaymentReturn] = Field()
    request_id: str = Field( description="A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.")

TransferRepaymentReturnListResponse.update_forward_refs()
