# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum


class TransferIntentAuthorizationDecision(str, Enum):
    APPROVED = "APPROVED"
    DECLINED = "DECLINED"

# Nullable OpenAPI enum
    @classmethod
    def __modify_schema__(cls, field_schema: dict) -> None:
        field_schema["nullable"] = True
