# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.transfer_ach_network import TransferACHNetwork




class TransferLedgerDepositRequest(BaseModel):
    """Defines the request schema for `/transfer/ledger/deposit`"""


    client_id: Optional[str] = Field(default=None, description="Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.")
    secret: Optional[str] = Field(default=None, description="Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.")
    originator_client_id: Optional[str] = Field(default=None, description="Client ID of the customer that owns the Ledger balance. This is so Plaid knows which of your customers to payout or collect funds. Only applicable for [Platform customers](https://plaid.com/docs/transfer/application/#originators-vs-platforms). Do not include if you’re paying out to yourself.")
    funding_account_id: Optional[str] = Field(default=None, description="Specify which funding account to use. Customers can find a list of `funding_account_id`s in the Accounts page of the Plaid Dashboard, under the \"Account ID\" column. If this field is left blank, the funding account associated with the specified Ledger will be used. If an `originator_client_id` is specified, the `funding_account_id` must belong to the specified originator.")
    ledger_id: Optional[str] = Field(default=None, description="Specify which ledger balance to deposit to. Customers can find a list of `ledger_id`s in the Accounts page of your Plaid Dashboard. If this field is left blank, this will default to id of the default ledger balance.")
    amount: str = Field( description="A positive amount of how much will be deposited into ledger (decimal string with two digits of precision e.g. \"5.50\").")
    description: Optional[str] = Field(default=None, description="The description of the deposit that will be passed to the receiving bank (up to 10 characters). Note that banks utilize this field differently, and may or may not show it on the bank statement.")
    idempotency_key: str = Field( description="A unique key provided by the client, per unique ledger deposit. Maximum of 50 characters.  The API supports idempotency for safely retrying the request without accidentally performing the same operation twice. For example, if a request to create a ledger deposit fails due to a network connection error, you can retry the request with the same idempotency key to guarantee that only a single deposit is created.")
    network: TransferACHNetwork = Field()

    @field_validator("description")
    @classmethod
    def description_max_length(cls, value):
        assert len(value) <= 10
        return value

    @field_validator("idempotency_key")
    @classmethod
    def idempotency_key_max_length(cls, value):
        assert len(value) <= 50
        return value

TransferLedgerDepositRequest.update_forward_refs()
