# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class TransferUserAddressInResponse(BaseModel):
    """The address associated with the account holder."""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#transfer_user_address_in_response"
            }
            , "nullable": True,
        }

    street: Optional[str] = Field(default=None, description="The street number and name (i.e., \"100 Market St.\").")
    city: Optional[str] = Field(default=None, description="Ex. \"San Francisco\"")
    region: Optional[str] = Field(default=None, description="The state or province (e.g., \"CA\").")
    postal_code: Optional[str] = Field(default=None, description="The postal code (e.g., \"94103\").")
    country: Optional[str] = Field(default=None, description="A two-letter country code (e.g., \"US\").")

TransferUserAddressInResponse.update_forward_refs()
