# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class UpdateIndividualScreeningRequestSearchTerms(BaseModel):
    """Search terms for editing an individual watchlist screening"""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#update_individual_screening_request_search_terms"
            }
        }

    watchlist_program_id: Optional[str] = Field(default=None, description="ID of the associated program.")
    legal_name: Optional[str] = Field(default=None, description="The legal name of the individual being screened.")
    date_of_birth: Optional[date] = Field(default=None, description="A date in the format YYYY-MM-DD (RFC 3339 Section 5.6).")
    document_number: Optional[str] = Field(default=None, description="The numeric or alphanumeric identifier associated with this document.")
    country: Optional[str] = Field(default=None, description="Valid, capitalized, two-letter ISO code representing the country of this object. Must be in ISO 3166-1 alpha-2 form.")

    @validator("legal_name")
    def legal_name_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("document_number")
    def document_number_min_length(cls, value):
        assert len(value) >= 4
        return value

    @validator("country")
    def country_min_length(cls, value):
        assert len(value) >= 2
        return value

UpdateIndividualScreeningRequestSearchTerms.update_forward_refs()
