# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum



class UserStatedIncomeSourceCategory(str, Enum):
    OTHER = "OTHER"
    SALARY = "SALARY"
    UNEMPLOYMENT = "UNEMPLOYMENT"
    CASH = "CASH"
    GIG_ECONOMY = "GIG_ECONOMY"
    RENTAL = "RENTAL"
    CHILD_SUPPORT = "CHILD_SUPPORT"
    MILITARY = "MILITARY"
    RETIREMENT = "RETIREMENT"
    LONG_TERM_DISABILITY = "LONG_TERM_DISABILITY"
    BANK_INTEREST = "BANK_INTEREST"
