# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class ValidationSource(BaseModel):
    """Documentation not found in the MISMO model viewer and not provided by Freddie Mac."""


    validation_source_name: Optional[str] = Field(default=None, description="Documentation not found in the MISMO model viewer and not provided by Freddie Mac.")
    validation_source_reference_identifier: Optional[str] = Field(default=None, description="Documentation not found in the MISMO model viewer and not provided by Freddie Mac.")

ValidationSource.update_forward_refs()
