# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.webhook_environment_values import WebhookEnvironmentValues




class VerificationExpiredWebhook(BaseModel):
    """Fired when an Item was not verified via automated micro-deposits after seven days since the automated micro-deposit was made."""


    webhook_type: str = Field( description="`AUTH`")
    webhook_code: str = Field( description="`VERIFICATION_EXPIRED`")
    item_id: str = Field( description="The `item_id` of the Item associated with this webhook, warning, or error")
    account_id: str = Field( description="The `account_id` of the account associated with the webhook")
    environment: WebhookEnvironmentValues = Field()

VerificationExpiredWebhook.update_forward_refs()
