# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401




class W2Box12(BaseModel):
    """Data on the W2 Box 12"""

    class Config:
        schema_extra = {
            "externalDocs": {
                "url": "https://plaid.com/docs/api/accounts/#w2_box12"
            }
        }

    code: Optional[str] = Field(default=None, description="W2 Box 12 code.")
    amount: Optional[str] = Field(default=None, description="W2 Box 12 amount.")

W2Box12.update_forward_refs()
