# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class WalletGetRequest(BaseModel):
    """WalletGetRequest defines the request schema for `/wallet/get`"""


    client_id: Optional[str] = Field(default=None, description="Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.")
    secret: Optional[str] = Field(default=None, description="Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.")
    wallet_id: str = Field( description="The ID of the e-wallet")

    @field_validator("wallet_id")
    @classmethod
    def wallet_id_min_length(cls, value):
        assert len(value) >= 1
        return value

WalletGetRequest.update_forward_refs()
