# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from strenum import StrEnum

WalletTransactionStatus = StrEnum("WalletTransactionStatus", names=['AUTHORISING', 'INITIATED', 'EXECUTED', 'SETTLED', 'BLOCKED', 'FAILED'])