# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date as date_  # noqa: F401
from datetime import datetime as datetime_  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, ConfigDict, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401




class WalletTransactionCounterpartyInternational(BaseModel):
    """International Bank Account Number for a Wallet Transaction"""
    model_config = ConfigDict(json_schema_extra={"nullable": True})

    iban: Optional[str] = Field(default=None, description="International Bank Account Number (IBAN).")

    @field_validator("iban")
    @classmethod
    def iban_min_length(cls, value):
        assert len(value) >= 15
        return value

    @field_validator("iban")
    @classmethod
    def iban_max_length(cls, value):
        assert len(value) <= 34
        return value

WalletTransactionCounterpartyInternational.update_forward_refs()
