# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from plaid_skel.models.update_individual_screening_request_search_terms import UpdateIndividualScreeningRequestSearchTerms
from plaid_skel.models.watchlist_screening_individual_update_request_resettable_field import WatchlistScreeningIndividualUpdateRequestResettableField
from plaid_skel.models.watchlist_screening_status import WatchlistScreeningStatus




class WatchlistScreeningIndividualUpdateRequest(BaseModel):
    """Request input for editing an individual watchlist screening"""


    watchlist_screening_id: str = Field( description="ID of the associated screening.")
    search_terms: Optional[UpdateIndividualScreeningRequestSearchTerms] = Field(default=None,)
    assignee: Optional[str] = Field(default=None, description="ID of the associated user.")
    status: Optional[WatchlistScreeningStatus] = Field(default=None,)
    client_user_id: Optional[str] = Field(default=None, description="An identifier to help you connect this object to your internal systems. For example, your database ID corresponding to this object.")
    client_id: Optional[str] = Field(default=None, description="Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.")
    secret: Optional[str] = Field(default=None, description="Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.")
    reset_fields: Optional[List[WatchlistScreeningIndividualUpdateRequestResettableField]] = Field(default=None, description="A list of fields to reset back to null")

    @validator("client_user_id")
    def client_user_id_min_length(cls, value):
        assert len(value) >= 1
        return value

WatchlistScreeningIndividualUpdateRequest.update_forward_refs()
