# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.




from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import field_validator, AnyUrl, BaseModel, EmailStr, Field  # noqa: F401
from plaid_skel.models.watchlist_screening_audit_trail import WatchlistScreeningAuditTrail
from plaid_skel.models.watchlist_screening_search_terms import WatchlistScreeningSearchTerms
from plaid_skel.models.watchlist_screening_status import WatchlistScreeningStatus




class WatchlistScreeningIndividualCreateResponse(BaseModel):
    """The screening object allows you to represent a customer in your system, update their profile, and search for them on various watchlists. Note: Rejected customers will not receive new hits, regardless of program configuration."""


    id: str = Field( description="ID of the associated screening.")
    search_terms: WatchlistScreeningSearchTerms = Field()
    assignee: Optional[str] = Field(default=None, description="ID of the associated user.")
    status: WatchlistScreeningStatus = Field()
    client_user_id: Optional[str] = Field(default=None, description="An identifier to help you connect this object to your internal systems. For example, your database ID corresponding to this object.")
    audit_trail: WatchlistScreeningAuditTrail = Field()
    request_id: str = Field( description="A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.")

    @field_validator("client_user_id")
    @classmethod
    def client_user_id_min_length(cls, value):
        assert len(value) >= 1
        return value

WatchlistScreeningIndividualCreateResponse.update_forward_refs()
