# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum

from pydantic import GetJsonSchemaHandler
from pydantic.json_schema import JsonSchemaValue


class WatchlistScreeningStatus(str, Enum):
    REJECTED = "rejected"
    PENDING_REVIEW = "pending_review"
    CLEARED = "cleared"
