# coding: utf-8
# AUTOGENERATED with MDM customization.  Do not edit.

from enum import Enum



class WebhookType(str, Enum):
    AUTH = "AUTH"
    HOLDINGS = "HOLDINGS"
    INVESTMENTS_TRANSACTIONS = "INVESTMENTS_TRANSACTIONS"
    ITEM = "ITEM"
    LIABILITIES = "LIABILITIES"
    TRANSACTIONS = "TRANSACTIONS"
    ASSETS = "ASSETS"
